"""Tests for profiles, install-tools --dry-run, font preview and the stale-config nudge."""

from pathlib import Path
from unittest.mock import patch

from typer.testing import CliRunner

from core.cli import app

runner = CliRunner()


def test_active_profile_reads_header(tmp_path: Path):
    from core.profiles import active_profile

    config_dir = tmp_path / "config"
    config_dir.mkdir()
    (config_dir / "settings.local.toml").write_text(
        "# Auto-generated by `my-shell setup --profile full`\n\n[integrations]\n",
        encoding="utf-8",
    )
    assert active_profile(tmp_path) == "full"


def test_active_profile_none_without_file(tmp_path: Path):
    from core.profiles import active_profile

    assert active_profile(tmp_path) is None


def test_active_profile_none_for_wizard_header(tmp_path: Path):
    from core.profiles import active_profile

    config_dir = tmp_path / "config"
    config_dir.mkdir()
    (config_dir / "settings.local.toml").write_text(
        "# Generated by `my-shell init`\n", encoding="utf-8"
    )
    assert active_profile(tmp_path) is None


def test_profiles_list_marks_active(tmp_project: Path):
    with (
        patch("core.utils.get_project_dir", return_value=tmp_project),
        patch("core.profiles.active_profile", return_value="full"),
    ):
        result = runner.invoke(app, ["profiles", "list"])
    assert result.exit_code == 0
    assert "minimal" in result.output
    assert "full" in result.output
    assert "Active profile" in result.output


def test_profiles_apply_unknown_exits_1(tmp_project: Path):
    with patch("core.profiles.get_project_dir", return_value=tmp_project):
        result = runner.invoke(app, ["profiles", "apply", "ghost"])
    assert result.exit_code == 1
    assert "Unknown profile" in result.output


def test_profiles_apply_writes_settings(tmp_project: Path):
    with patch("core.profiles.get_project_dir", return_value=tmp_project):
        result = runner.invoke(app, ["profiles", "apply", "minimal"])
    assert result.exit_code == 0
    assert (tmp_project / "config" / "settings.local.toml").exists()


def test_resolve_install_command_unknown_tool():
    from core.install import resolve_install_command

    assert resolve_install_command("no-such-tool") is None


def test_resolve_install_command_uses_detected_pkg():
    """Without mise, resolution falls back to the detected package manager."""
    from core.install import resolve_install_command

    with (
        patch("core.install.detect_package_manager", return_value="homebrew"),
        patch("core.install.is_available", side_effect=lambda t: t != "mise"),
    ):
        cmd = resolve_install_command("fzf")
    assert cmd is not None
    assert cmd[:2] == ["brew", "install"]


def test_install_tools_dry_run_single(tmp_project: Path):
    with (
        patch("core.utils.get_project_dir", return_value=tmp_project),
        patch("core.install.detect_package_manager", return_value="homebrew"),
        patch("core.install.is_available", side_effect=lambda t: t != "mise"),
        patch("core.install._run") as mock_run,
    ):
        result = runner.invoke(app, ["install-tools", "fzf", "--dry-run"])
    assert result.exit_code == 0
    assert "brew install fzf" in result.output
    mock_run.assert_not_called()  # dry-run never installs


def test_install_tools_dry_run_all(tmp_project: Path):
    with (
        patch("core.utils.get_project_dir", return_value=tmp_project),
        patch("core.config.load_settings", return_value={}),
        patch("core.config.is_integration_enabled", return_value=True),
        patch("core.install.detect_package_manager", return_value="homebrew"),
        patch("core.install.is_available", return_value=False),
        patch("core.install._run") as mock_run,
    ):
        result = runner.invoke(app, ["install-tools", "--dry-run"])
    assert result.exit_code == 0
    assert "dry-run" in result.output.lower()
    mock_run.assert_not_called()


def test_font_preview_utf_shows_glyphs():
    from core.fonts import font_preview

    class _Utf:
        encoding = "utf-8"

    with patch("core.fonts.sys.stdout", _Utf()):
        text = font_preview("meslo")
    assert "Meslo LG Nerd Font" in text
    assert "Glyph sample" in text


def test_font_preview_non_utf_ascii_only():
    from core.fonts import font_preview

    class _Ascii:
        encoding = "cp1252"

    with patch("core.fonts.sys.stdout", _Ascii()):
        text = font_preview("meslo")
    assert "Glyph sample" not in text
    assert "Set your terminal font" in text


def test_status_deployed_up_to_date():
    from core.merge import DeployStatus

    st = DeployStatus("nushell", True, "v1", "v1", "aaa", "aaa")
    with patch("core.merge.get_deploy_statuses", return_value=[st]):
        result = runner.invoke(app, ["status", "--shell", "nushell"])
    assert result.exit_code == 0
    assert "Deployed version: v1" in result.output
    assert "Up to date" in result.output


def test_status_deployed_stale():
    from core.merge import DeployStatus

    st = DeployStatus("nushell", True, "v1", "v2", "aaa", "bbb")
    with patch("core.merge.get_deploy_statuses", return_value=[st]):
        result = runner.invoke(app, ["status", "--shell", "nushell"])
    assert result.exit_code == 0
    assert "Re-deploy needed" in result.output
    assert "my-shell setup --shell nushell" in result.output


def test_maybe_nudge_stale_skips_without_tty():
    """No tty -> the nudge does nothing (no cache write, no cost)."""
    from core.cli import _maybe_nudge_stale

    with (
        patch("core.cli.sys.stdout.isatty", return_value=False),
        patch("core.merge.get_deploy_statuses") as mock_statuses,
    ):
        _maybe_nudge_stale()
    mock_statuses.assert_not_called()


def test_maybe_nudge_stale_warns_when_stale(tmp_path: Path, capsys):
    from core.cli import _maybe_nudge_stale
    from core.merge import DeployStatus

    stale = DeployStatus("nushell", True, "v1", "v2", "aaa", "bbb")
    with (
        patch("core.cli.sys.stdout.isatty", return_value=True),
        patch("core.utils.get_cache_dir", return_value=tmp_path),
        patch("core.merge.get_deploy_statuses", return_value=[stale]),
    ):
        _maybe_nudge_stale()
    err = capsys.readouterr().err
    assert "config changed since last deploy" in err
    assert (tmp_path / "last-stale-nudge").exists()


def test_maybe_nudge_stale_throttles(tmp_path: Path):
    from core.cli import _maybe_nudge_stale
    from core.merge import DeployStatus

    (tmp_path / "last-stale-nudge").write_text("99999999999.0", encoding="utf-8")  # far future
    stale = DeployStatus("nushell", True, "v1", "v2", "aaa", "bbb")
    with (
        patch("core.cli.sys.stdout.isatty", return_value=True),
        patch("core.utils.get_cache_dir", return_value=tmp_path),
        patch("core.merge.get_deploy_statuses", return_value=[stale]) as mock_statuses,
    ):
        _maybe_nudge_stale()
    mock_statuses.assert_not_called()  # throttled, never checked
