"""End-to-end tests for CLI commands, driven through Typer's CliRunner."""

import subprocess
from contextlib import ExitStack
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from typer.testing import CliRunner

from core.cli import app
from core.registry import XONTRIB_PACKAGES
from tests._helpers import apply_isolation_patches as _apply_patches

runner = CliRunner()


def test_cli_verbose_flag_enables_debug(tmp_project: Path, tmp_path: Path):
    """--verbose should enable debug output with [debug] markers."""
    config_dir = tmp_path / "nu_cfg"
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    with ExitStack() as stack:
        _apply_patches(stack, tmp_project, fake_home)
        stack.enter_context(patch("core.merge.get_config_dir", return_value=config_dir))
        stack.enter_context(patch("core.config.get_config_dir", return_value=config_dir))
        result = runner.invoke(app, ["--verbose", "deploy", "--shell", "nushell"])

    assert result.exit_code == 0, result.output
    assert "[debug]" in result.output


def test_cli_detect():
    result = runner.invoke(app, ["detect"])
    assert result.exit_code == 0
    assert "System Detection" in result.output
    assert "Tool Status" in result.output
    assert "OS:" in result.output
    assert "Current Shell:" in result.output


@pytest.mark.parametrize(
    "shell, expected_file",
    [
        ("nushell", "shells/nushell/aliases.nu"),
        ("xonsh", "shells/xonsh/aliases.xsh"),
    ],
)
def test_cli_render(tmp_project: Path, shell: str, expected_file: str):
    with patch("core.render.get_project_dir", return_value=tmp_project):
        result = runner.invoke(app, ["render", "--shell", shell])

    assert result.exit_code == 0
    assert f"aliases for {shell}" in result.output
    assert (tmp_project / expected_file).exists()


def test_cli_render_all(tmp_project: Path):
    with patch("core.render.get_project_dir", return_value=tmp_project):
        result = runner.invoke(app, ["render", "--shell", "all"])

    assert result.exit_code == 0
    assert "aliases for nushell" in result.output
    assert "aliases for xonsh" in result.output
    assert (tmp_project / "shells" / "nushell" / "aliases.nu").exists()
    assert (tmp_project / "shells" / "xonsh" / "aliases.xsh").exists()


def test_cli_render_preview_does_not_write(tmp_project: Path):
    """render --preview prints the rendered aliases and writes no file."""
    with patch("core.render.get_project_dir", return_value=tmp_project):
        result = runner.invoke(app, ["render", "--shell", "nushell", "--preview"])

    assert result.exit_code == 0
    assert "aliases" in result.output.lower()
    assert not (tmp_project / "shells" / "nushell" / "aliases.nu").exists()


def test_cli_deploy_nushell(tmp_project: Path, tmp_path: Path):
    config_dir = tmp_path / "nu_cfg"
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    with ExitStack() as stack:
        _apply_patches(stack, tmp_project, fake_home)
        stack.enter_context(patch("core.merge.get_config_dir", return_value=config_dir))
        stack.enter_context(patch("core.config.get_config_dir", return_value=config_dir))
        result = runner.invoke(app, ["deploy", "--shell", "nushell"])

    assert result.exit_code == 0, result.output
    assert (config_dir / "config.nu").exists()
    assert (config_dir / "env.nu").exists()
    assert (config_dir / "user-custom.nu").exists()
    assert (config_dir / "user-env.nu").exists()

    content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "Generated by my-shell" in content


def test_cli_deploy_xonsh(tmp_project: Path, tmp_path: Path):
    config_dir = tmp_path / "xonsh_cfg"
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    with ExitStack() as stack:
        _apply_patches(stack, tmp_project, fake_home)
        stack.enter_context(patch("core.merge.get_config_dir", return_value=config_dir))
        stack.enter_context(patch("core.config.get_config_dir", return_value=config_dir))
        result = runner.invoke(app, ["deploy", "--shell", "xonsh"])

    assert result.exit_code == 0
    assert (fake_home / ".xonshrc").exists()
    assert (config_dir / "user-custom.xsh").exists()

    content = (fake_home / ".xonshrc").read_text(encoding="utf-8")
    assert "Generated by my-shell" in content


def test_cli_deploy_default_uses_enabled_shells(tmp_project: Path, tmp_path: Path):
    """The omitted target respects the configured xonsh opt-out."""
    nu_cfg = tmp_path / "nu_cfg"
    xonsh_cfg = tmp_path / "xonsh_cfg"
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    def _config_dir_for(shell: str):
        return nu_cfg if shell == "nushell" else xonsh_cfg

    with ExitStack() as stack:
        _apply_patches(stack, tmp_project, fake_home)
        stack.enter_context(patch("core.merge.get_config_dir", side_effect=_config_dir_for))
        stack.enter_context(patch("core.config.get_config_dir", side_effect=_config_dir_for))
        result = runner.invoke(app, ["deploy"])

    assert result.exit_code == 0
    assert (nu_cfg / "config.nu").exists()
    assert (nu_cfg / "env.nu").exists()
    assert not (fake_home / ".xonshrc").exists()


@pytest.mark.parametrize(
    "shell, aliases_path, expected_alias",
    [
        ("nushell", "shells/nushell/aliases.nu", "alias g = git"),
        ("xonsh", "shells/xonsh/aliases.xsh", "aliases['g'] = ['git']"),
    ],
)
def test_cli_deploy_renders_aliases(
    tmp_project: Path, tmp_path: Path, shell: str, aliases_path: str, expected_alias: str
):
    """Deploy triggers alias rendering as a side effect."""
    config_dir = tmp_path / f"{shell}_cfg"
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    with ExitStack() as stack:
        _apply_patches(stack, tmp_project, fake_home)
        stack.enter_context(patch("core.merge.get_config_dir", return_value=config_dir))
        stack.enter_context(patch("core.config.get_config_dir", return_value=config_dir))
        result = runner.invoke(app, ["deploy", "--shell", shell])

    assert result.exit_code == 0
    aliases_file = tmp_project / aliases_path
    assert aliases_file.exists()
    content = aliases_file.read_text(encoding="utf-8")
    assert expected_alias in content


def test_cli_deploy_preserves_user_custom(tmp_project: Path, tmp_path: Path):
    """Deploying twice does NOT overwrite user-custom files."""
    config_dir = tmp_path / "nu_cfg"
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    def _do_deploy():
        with ExitStack() as stack:
            _apply_patches(stack, tmp_project, fake_home)
            stack.enter_context(patch("core.merge.get_config_dir", return_value=config_dir))
            stack.enter_context(patch("core.config.get_config_dir", return_value=config_dir))
            return runner.invoke(app, ["deploy", "--shell", "nushell"])

    result = _do_deploy()
    assert result.exit_code == 0
    user_custom = config_dir / "user-custom.nu"
    assert user_custom.exists()

    user_custom.write_text("# my personal config\n", encoding="utf-8")

    result = _do_deploy()
    assert result.exit_code == 0
    assert user_custom.read_text(encoding="utf-8") == "# my personal config\n"


@pytest.mark.parametrize(
    "shell, config_key",
    [
        ("nushell", "nu_cfg"),
        ("xonsh", "xonsh_cfg"),
    ],
)
def test_cli_setup(
    tmp_project: Path,
    tmp_path: Path,
    shell: str,
    config_key: str,
):
    """Full setup: render + deploy."""
    config_dir = tmp_path / config_key
    config_dir.mkdir()
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    with ExitStack() as stack:
        _apply_patches(stack, tmp_project, fake_home)
        stack.enter_context(patch("core.merge.get_config_dir", return_value=config_dir))
        stack.enter_context(patch("core.config.get_config_dir", return_value=config_dir))
        result = runner.invoke(app, ["setup", "--shell", shell])

    assert result.exit_code == 0
    assert f"Setting up {shell}" in result.output

    # New config was deployed
    if shell == "nushell":
        content = (config_dir / "config.nu").read_text(encoding="utf-8")
        assert "Generated by my-shell" in content
        assert (tmp_project / "shells" / "nushell" / "aliases.nu").exists()
    elif shell == "xonsh":
        content = (fake_home / ".xonshrc").read_text(encoding="utf-8")
        assert "Generated by my-shell" in content
        assert (tmp_project / "shells" / "xonsh" / "aliases.xsh").exists()


def test_cli_setup_default_uses_enabled_shells(tmp_project: Path, tmp_path: Path):
    """Omitting --shell deploys only shells enabled in settings."""
    nu_cfg = tmp_path / "nu_cfg"
    xonsh_cfg = tmp_path / "xonsh_cfg"
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    def _config_dir_for(shell: str):
        return nu_cfg if shell == "nushell" else xonsh_cfg

    with ExitStack() as stack:
        _apply_patches(stack, tmp_project, fake_home)
        stack.enter_context(patch("core.merge.get_config_dir", side_effect=_config_dir_for))
        stack.enter_context(patch("core.config.get_config_dir", side_effect=_config_dir_for))
        result = runner.invoke(app, ["setup"])

    assert result.exit_code == 0
    assert "Setting up nushell" in result.output
    assert "Setting up xonsh" not in result.output
    assert (nu_cfg / "config.nu").exists()
    assert not (fake_home / ".xonshrc").exists()


def test_cli_setup_install_xonsh_opts_into_deploy(tmp_project: Path, tmp_path: Path):
    nu_cfg = tmp_path / "nu_cfg"
    xonsh_cfg = tmp_path / "xonsh_cfg"
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    def _config_dir_for(shell: str):
        return nu_cfg if shell == "nushell" else xonsh_cfg

    with ExitStack() as stack:
        _apply_patches(stack, tmp_project, fake_home)
        stack.enter_context(patch("core.merge.get_config_dir", side_effect=_config_dir_for))
        stack.enter_context(patch("core.config.get_config_dir", side_effect=_config_dir_for))
        result = runner.invoke(app, ["setup", "--install-xonsh"])

    assert result.exit_code == 0
    assert "Setting up nushell" in result.output
    assert "Setting up xonsh" in result.output
    assert (fake_home / ".xonshrc").exists()


def test_cli_setup_exits_on_failure():
    """setup exits with code 1 when deploy raises."""
    with (
        patch("core.install.install_shells_for_setup"),
        patch("core.install.install_all_tools"),
        patch("core.merge.deploy", side_effect=RuntimeError("boom")),
    ):
        result = runner.invoke(app, ["setup", "--shell", "nushell"])
    assert result.exit_code == 1


def test_cli_setup_classifies_shell_install_failure():
    with patch("core.install.install_shells_for_setup", side_effect=RuntimeError("offline")):
        result = runner.invoke(app, ["setup", "--shell", "nushell"])

    assert result.exit_code == 1
    assert "Shell install failed: offline" in result.output


def test_cli_render_exits_on_failure():
    """render exits with code 1 when render_aliases raises."""
    with patch("core.render.render_aliases", side_effect=RuntimeError("boom")):
        result = runner.invoke(app, ["render", "--shell", "nushell"])
    assert result.exit_code == 1


def test_cli_deploy_cmd_exits_on_failure():
    """deploy exits with code 1 when deploy raises."""
    with patch("core.merge.deploy", side_effect=RuntimeError("boom")):
        result = runner.invoke(app, ["deploy", "--shell", "nushell"])
    assert result.exit_code == 1


def test_cli_install_nushell():
    mock_run = MagicMock()
    with (
        patch("core.install.is_available", return_value=False),
        patch("core.install.detect_package_manager", return_value="winget"),
        patch("core.install.subprocess.run", mock_run),
        patch("core.install.shutil.which", return_value="/usr/bin/nu"),
    ):
        result = runner.invoke(app, ["install", "--shell", "nushell"])

    assert result.exit_code == 0
    mock_run.assert_called_once_with(
        [
            "winget",
            "install",
            "--id",
            "Nushell.Nushell",
            "-e",
            "--accept-source-agreements",
            "--accept-package-agreements",
            "--disable-interactivity",
        ],
        check=True,
        stdin=subprocess.DEVNULL,
        timeout=120,
    )


def test_cli_install_xonsh():
    mock_run = MagicMock()
    with (
        patch("core.install.is_available", side_effect=lambda t: t == "uv"),
        patch("core.install.subprocess.run", mock_run),
        patch("core.install.shutil.which", return_value="/usr/bin/xonsh"),
    ):
        result = runner.invoke(app, ["install", "--shell", "xonsh"])

    assert result.exit_code == 0
    mock_run.assert_called_once()
    command = mock_run.call_args.args[0]
    assert command[:4] == ["uv", "tool", "install", "xonsh[full]"]
    for package in XONTRIB_PACKAGES:
        assert package in command
    assert mock_run.call_args.kwargs == {
        "check": True,
        "stdin": subprocess.DEVNULL,
        "timeout": 120,
    }


def test_cli_install_all():
    mock_run = MagicMock()

    def _avail(tool):
        # Shells not installed, but uv is available for xonsh install
        return tool == "uv"

    with (
        patch("core.install.is_available", side_effect=_avail),
        patch("core.install.detect_package_manager", return_value="homebrew"),
        patch("core.install.subprocess.run", mock_run),
        patch("core.install.shutil.which", return_value="/some/path"),
    ):
        result = runner.invoke(app, ["install", "--shell", "all"])

    assert result.exit_code == 0
    assert mock_run.call_count == 2
    cmds = [c.args[0] for c in mock_run.call_args_list]
    assert any("nushell" in str(c) for c in cmds)
    assert any("xonsh" in str(c) for c in cmds)


def test_cli_install_tools_single():
    """install-tools with a specific tool name."""
    with patch("core.install.install_tool") as mock_install:
        result = runner.invoke(app, ["install-tools", "atuin"])

    assert result.exit_code == 0
    mock_install.assert_called_once_with("atuin")


def test_cli_install_tools_all():
    """install-tools without args installs all tools."""
    with patch("core.install.install_all_tools") as mock_install:
        result = runner.invoke(app, ["install-tools"])

    assert result.exit_code == 0
    mock_install.assert_called_once()


def test_cli_install_tools_exits_on_failure():
    """install-tools exits with code 1 on error."""
    with patch("core.install.install_tool", side_effect=RuntimeError("boom")):
        result = runner.invoke(app, ["install-tools", "atuin"])

    assert result.exit_code == 1


def test_cli_plugins_status(tmp_project: Path):
    """plugins status prints plugin info and exits cleanly."""
    with ExitStack() as stack:
        stack.enter_context(patch("core.plugins.is_plugin_installed", return_value=False))
        stack.enter_context(patch("core.utils.get_project_dir", return_value=tmp_project))
        result = runner.invoke(app, ["plugins", "status"])

    assert result.exit_code == 0
    assert "cargo:" in result.output
    assert "nu:" in result.output


def test_cli_full_roundtrip(tmp_project: Path, tmp_path: Path):
    """Complete user workflow: deploy -> user edits user-custom -> redeploy preserves it."""
    config_dir = tmp_path / "nu_cfg"
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    def _do_setup():
        with ExitStack() as stack:
            _apply_patches(stack, tmp_project, fake_home)
            stack.enter_context(patch("core.merge.get_config_dir", return_value=config_dir))
            stack.enter_context(patch("core.config.get_config_dir", return_value=config_dir))
            return runner.invoke(app, ["setup", "--shell", "nushell"])

    result = _do_setup()
    assert result.exit_code == 0

    config_nu = config_dir / "config.nu"
    assert config_nu.exists()
    assert "Generated by my-shell" in config_nu.read_text(encoding="utf-8")

    user_custom = config_dir / "user-custom.nu"
    user_custom.write_text("# I customized this myself\n", encoding="utf-8")

    result = _do_setup()
    assert result.exit_code == 0
    assert "Generated by my-shell" in config_nu.read_text(encoding="utf-8")

    assert user_custom.read_text(encoding="utf-8") == "# I customized this myself\n"


def test_cli_plugins_install(tmp_project: Path):
    """plugins install invokes install_plugins and exits cleanly."""
    mock_install = MagicMock(return_value=True)
    with ExitStack() as stack:
        stack.enter_context(patch("core.utils.get_project_dir", return_value=tmp_project))
        stack.enter_context(patch("core.plugins.install_plugins", mock_install))
        result = runner.invoke(app, ["plugins", "install"])

    assert result.exit_code == 0
    mock_install.assert_called_once_with(tmp_project)


def test_cli_plugins_register(tmp_project: Path):
    """plugins register invokes register_plugins and exits cleanly."""
    mock_register = MagicMock(return_value=True)
    with ExitStack() as stack:
        stack.enter_context(patch("core.utils.get_project_dir", return_value=tmp_project))
        stack.enter_context(patch("core.plugins.register_plugins", mock_register))
        result = runner.invoke(app, ["plugins", "register"])

    assert result.exit_code == 0
    mock_register.assert_called_once_with(tmp_project)


def test_cli_plugins_setup(tmp_project: Path):
    """plugins setup invokes install_plugins then register_plugins."""
    mock_install = MagicMock(return_value=True)
    mock_register = MagicMock(return_value=True)
    with ExitStack() as stack:
        stack.enter_context(patch("core.utils.get_project_dir", return_value=tmp_project))
        stack.enter_context(patch("core.plugins.install_plugins", mock_install))
        stack.enter_context(patch("core.plugins.register_plugins", mock_register))
        result = runner.invoke(app, ["plugins", "setup"])

    assert result.exit_code == 0
    mock_install.assert_called_once_with(tmp_project)
    mock_register.assert_called_once_with(tmp_project)
