"""Edge paths in backup, uninstall and profiles that the main suites do not reach."""

from pathlib import Path
from unittest.mock import patch

from core.backup import preview_restore, restore_backup
from core.profiles import active_profile
from core.uninstall import uninstall_shell


def test_active_profile_none_for_empty_settings_local(tmp_path: Path):
    """An empty settings.local.toml has no header line to read a profile name from."""
    (tmp_path / "config").mkdir()
    (tmp_path / "config" / "settings.local.toml").write_text("", encoding="utf-8")

    assert active_profile(project_dir=tmp_path) is None


def test_restore_backup_ignores_directories_inside_the_backup(tmp_path: Path):
    """A stray directory in a backup folder is skipped, not treated as a config file."""
    backup_dir = tmp_path / "backup"
    backup_dir.mkdir()
    (backup_dir / "config.nu").write_text("# restored\n", encoding="utf-8")
    (backup_dir / "nested").mkdir()

    config_dir = tmp_path / "nu"
    config_dir.mkdir()

    restore_backup(backup_dir, config_dir, "nushell")

    assert (config_dir / "config.nu").read_text(encoding="utf-8") == "# restored\n"
    assert not (config_dir / "nested").exists()


def test_preview_restore_skips_user_files(tmp_path: Path):
    """Layer 3 files are never restored, so they must not show up as a pending change."""
    backup_dir = tmp_path / "backup"
    backup_dir.mkdir()
    (backup_dir / "user-custom.nu").write_text("# mine\n", encoding="utf-8")

    config_dir = tmp_path / "nu"
    config_dir.mkdir()

    assert preview_restore(backup_dir, config_dir, "nushell") is False


def test_uninstall_xonsh_removes_user_custom_when_not_kept(tmp_path: Path):
    """--no-keep-custom deletes the xonsh user-custom file too."""
    config_dir = tmp_path / "xonsh"
    config_dir.mkdir()
    custom = config_dir / "user-custom.xsh"
    custom.write_text("# mine\n", encoding="utf-8")
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    with patch("core.uninstall.get_home_dir", return_value=fake_home):
        removed = uninstall_shell("xonsh", config_dir, keep_custom=False)

    assert not custom.exists()
    assert str(custom) in removed


def test_uninstall_xonsh_removes_the_generated_rc_from_home(tmp_path: Path):
    """The rc lives in home, not in the config dir -- uninstall has to reach it."""
    config_dir = tmp_path / "xonsh"
    config_dir.mkdir()
    fake_home = tmp_path / "home"
    fake_home.mkdir()
    rc = fake_home / ".xonshrc"
    rc.write_text("# Generated by my-shell\n", encoding="utf-8")

    with patch("core.uninstall.get_home_dir", return_value=fake_home):
        removed = uninstall_shell("xonsh", config_dir)

    assert not rc.exists()
    assert str(rc) in removed


def test_uninstall_xonsh_keeps_a_handwritten_rc(tmp_path: Path):
    config_dir = tmp_path / "xonsh"
    config_dir.mkdir()
    fake_home = tmp_path / "home"
    fake_home.mkdir()
    rc = fake_home / ".xonshrc"
    rc.write_text("# mine, written before my-shell\n", encoding="utf-8")

    with patch("core.uninstall.get_home_dir", return_value=fake_home):
        uninstall_shell("xonsh", config_dir)

    assert rc.exists()
