"""Tests for deploy() and _deploy_nushell() -- file creation, preservation, tool init."""

import os
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from core.merge import (
    ToolInitSpec,
    _deploy_delta_gitconfig,
    _deploy_nushell,
    _ensure_nushell_tool_init,
    _generate_tool_init,
    _get_version,
    _nushell_init_has_errors,
    _nushell_tool_init_specs,
    _preflight_validate,
    _render_tool_init,
    _warn_stale_config,
    deploy,
)
from core.mise import CommandSpec, resolve_command


def _resolved_tool_name(cmd: list[str]) -> str:
    """Return the executable stem for a resolved subprocess command."""
    return Path(cmd[0]).stem


def test_deploy_nushell_creates_files(tmp_project: Path):
    """Deploy should create config.nu, env.nu, and placeholder files."""
    config_dir = tmp_project / "deploy_test_nushell"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    assert (config_dir / "config.nu").exists()
    assert (config_dir / "env.nu").exists()
    assert (config_dir / "user-custom.nu").exists()
    assert (config_dir / "user-env.nu").exists()

    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "LAYER 1" in config_content
    assert "LAYER 2" in config_content
    assert "LAYER 3" in config_content


def test_deploy_nushell_writes_stub_init_files_when_tools_missing(tmp_project: Path):
    """Enabled Nushell integrations should still get managed stub files when tools are missing."""
    config_dir = tmp_project / "deploy_test_nushell_missing_integrations"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    atuin_stub = (config_dir / "atuin.nu").read_text(encoding="utf-8")
    assert "Generated by my-shell" in atuin_stub
    assert "Atuin" in atuin_stub
    assert "Not installed" in atuin_stub


def test_deploy_nushell_renders_aliases(tmp_project: Path):
    """Deploy should generate the aliases.nu file."""
    config_dir = tmp_project / "deploy_test_nu2"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    aliases_file = tmp_project / "shells" / "nushell" / "aliases.nu"
    assert aliases_file.exists()
    content = aliases_file.read_text(encoding="utf-8")
    assert "alias g = git" in content


def test_parse_alias_names_nushell(tmp_path: Path):
    """Nushell parser reads alias names (incl. punctuation) and skips wrapper defs."""
    from core.merge import _parse_alias_names

    f = tmp_path / "aliases.nu"
    f.write_text(
        "# header\nalias .. = cd ..\nalias g = git\n"
        'export def --wrapped fd [...args] { _run_wrapper "fd" "fdfind" "e" ...$args }\n',
        encoding="utf-8",
    )
    assert _parse_alias_names("nushell", f) == {"..", "g"}


def test_parse_alias_names_xonsh_excludes_wrappers(tmp_path: Path):
    """Xonsh parser reads LHS alias names and skips make_wrapper lines + RHS refs."""
    from core.merge import _parse_alias_names

    f = tmp_path / "aliases.xsh"
    f.write_text(
        "aliases['fd'] = make_wrapper('fd', 'fdfind', 'e')\n"
        "aliases['..'] = lambda args, stdin=None: os.chdir('..')\n"
        "aliases['ll'] = aliases['ls']\n",
        encoding="utf-8",
    )
    # fd is a wrapper (skipped); ls appears only as a RHS ref (not an LHS def).
    assert _parse_alias_names("xonsh", f) == {"..", "ll"}


def test_parse_alias_names_missing_file(tmp_path: Path):
    from core.merge import _parse_alias_names

    assert _parse_alias_names("nushell", tmp_path / "nope.nu") == set()


def test_deploy_reports_alias_delta(tmp_project: Path):
    """Re-deploy after editing aliases.toml reports the added/removed alias names."""
    config_dir = tmp_project / "deploy_delta"
    aliases_toml = tmp_project / "config" / "aliases.toml"

    with patch("core.merge.is_available", return_value=False):
        first = deploy("nushell", config_dir=config_dir, project_dir=tmp_project)
        # First render: no prior file, so every alias reads as added, none removed.
        assert "g" in first.aliases_added
        assert first.aliases_removed == []

        # Add one alias, remove one (drop the whole git group's `glog`).
        text = aliases_toml.read_text(encoding="utf-8")
        text = text.replace('glog = "git log --oneline --graph --decorate"\n', "")
        text += '\n[extra]\nzzt = "echo hi"\n'
        aliases_toml.write_text(text, encoding="utf-8")

        second = deploy("nushell", config_dir=config_dir, project_dir=tmp_project, force=True)

    assert second.aliases_added == ["zzt"]
    assert second.aliases_removed == ["glog"]


def test_deploy_xonsh_creates_files(tmp_project: Path):
    """Deploy xonsh should create xonshrc and placeholder."""
    config_dir = tmp_project / "deploy_test_xonsh"
    fake_home = tmp_project / "fake_home"
    fake_home.mkdir()

    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.get_home_dir", return_value=fake_home),
        patch("core.merge._find_xonsh_python", return_value=None),
    ):
        deploy("xonsh", config_dir=config_dir, project_dir=tmp_project)

    assert (fake_home / ".xonshrc").exists()
    assert (config_dir / "user-custom.xsh").exists()

    xonshrc = (fake_home / ".xonshrc").read_text(encoding="utf-8")
    assert "LAYER 1" in xonshrc
    assert "LAYER 2" in xonshrc
    assert "LAYER 3" in xonshrc


def test_deploy_xonsh_preserves_user_custom(tmp_project: Path):
    """Re-deploying xonsh should NOT overwrite user-custom.xsh."""
    config_dir = tmp_project / "deploy_test_xonsh_preserve"
    fake_home = tmp_project / "fake_home_preserve"
    fake_home.mkdir()

    patches = (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.get_home_dir", return_value=fake_home),
        patch("core.merge._find_xonsh_python", return_value=None),
    )

    with patches[0], patches[1], patches[2]:
        deploy("xonsh", config_dir=config_dir, project_dir=tmp_project)
    assert (config_dir / "user-custom.xsh").exists()

    (config_dir / "user-custom.xsh").write_text("# my stuff\n", encoding="utf-8")

    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.get_home_dir", return_value=fake_home),
        patch("core.merge._find_xonsh_python", return_value=None),
    ):
        result = deploy("xonsh", config_dir=config_dir, project_dir=tmp_project, force=True)

    assert (config_dir / "user-custom.xsh").read_text(encoding="utf-8") == "# my stuff\n"
    assert any("user-custom.xsh" in f for f in result.files_preserved)


def test_deploy_xonsh_preserves_integration_files(tmp_project: Path):
    """Deploy should NOT overwrite hand-crafted init.xsh integration files."""
    config_dir = tmp_project / "deploy_test_xonsh2"
    fake_home = tmp_project / "fake_home2"
    fake_home.mkdir()

    omp_init = tmp_project / "shells" / "xonsh" / "integrations" / "oh-my-posh" / "init.xsh"
    zoxide_init = tmp_project / "shells" / "xonsh" / "integrations" / "zoxide" / "init.xsh"
    original_omp = omp_init.read_text(encoding="utf-8")
    original_zoxide = zoxide_init.read_text(encoding="utf-8")

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.get_home_dir", return_value=fake_home),
        patch("core.merge._find_xonsh_python", return_value=None),
    ):
        deploy("xonsh", config_dir=config_dir, project_dir=tmp_project)

    assert omp_init.read_text(encoding="utf-8") == original_omp
    assert zoxide_init.read_text(encoding="utf-8") == original_zoxide


def test_deploy_unsupported_shell_raises(tmp_project: Path):
    with pytest.raises(ValueError, match="Unsupported shell"):
        deploy("fish", project_dir=tmp_project)


def test_deploy_xonsh_count_reflects_actual_install(tmp_project: Path):
    """DeployResult.xontrib_count comes from the real install, not a constant."""
    config_dir = tmp_project / "deploy_xontrib_count"
    fake_home = tmp_project / "fake_home_count"
    fake_home.mkdir()

    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.get_home_dir", return_value=fake_home),
        patch("core.merge._install_xontribs", return_value=3),
    ):
        result = deploy("xonsh", config_dir=config_dir, project_dir=tmp_project)

    assert result.xontrib_count == 3


def test_deploy_xonsh_count_zero_when_install_fails(tmp_project: Path):
    """A failed xontrib install yields a zero count, not an overclaim."""
    config_dir = tmp_project / "deploy_xontrib_zero"
    fake_home = tmp_project / "fake_home_zero"
    fake_home.mkdir()

    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.get_home_dir", return_value=fake_home),
        patch("core.merge._install_xontribs", return_value=0),
    ):
        result = deploy("xonsh", config_dir=config_dir, project_dir=tmp_project)

    assert result.xontrib_count == 0


def test_deploy_nushell_config_has_version(tmp_project: Path):
    """Deployed nushell config should contain MY_SHELL_VERSION and MY_SHELL_HASH."""
    config_dir = tmp_project / "deploy_test_version"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "$env.MY_SHELL_VERSION" in config_content
    assert "$env.MY_SHELL_HASH" in config_content


def test_deploy_xonsh_config_has_version(tmp_project: Path):
    """Deployed xonsh config should contain MY_SHELL_VERSION and MY_SHELL_HASH."""
    config_dir = tmp_project / "deploy_test_xonsh_version"
    fake_home = tmp_project / "fake_home_version"
    fake_home.mkdir()

    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.get_home_dir", return_value=fake_home),
        patch("core.merge._find_xonsh_python", return_value=None),
    ):
        deploy("xonsh", config_dir=config_dir, project_dir=tmp_project)

    xonshrc = (fake_home / ".xonshrc").read_text(encoding="utf-8")
    assert "$MY_SHELL_VERSION" in xonshrc
    assert "$MY_SHELL_HASH" in xonshrc


def test_deploy_shows_first_deploy(tmp_project: Path, capsys):
    """First deploy should show '(first deploy)' in output."""
    config_dir = tmp_project / "deploy_version_first"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    output = capsys.readouterr().out
    assert "first deploy" in output


def test_deploy_skips_when_unchanged(tmp_project: Path, capsys):
    """Re-deploying with same content should skip and show skip message."""
    config_dir = tmp_project / "deploy_version_unchanged"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    output = capsys.readouterr().out
    assert "unchanged" in output
    assert "skipping" in output


def test_deploy_does_not_skip_when_env_nu_is_missing(tmp_project: Path):
    """The hash marker alone must not stand in for a finished deploy."""
    config_dir = tmp_project / "deploy_interrupted"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)
        (config_dir / "env.nu").unlink()
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    assert (config_dir / "env.nu").exists()


def test_deploy_does_not_skip_when_a_sourced_file_is_missing(tmp_project: Path):
    """A deployed config that sources a file that is gone must be regenerated."""
    config_dir = tmp_project / "deploy_lost_source"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)
        (config_dir / "user-custom.nu").unlink()
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    assert (config_dir / "user-custom.nu").exists()


def test_deploy_writes_config_nu_last(tmp_project: Path):
    """config.nu carries the hash, so it must be the last file written."""
    config_dir = tmp_project / "deploy_order"
    written: list[str] = []
    from core.utils import atomic_write_text

    def _record(path, content):
        written.append(path.name)
        return atomic_write_text(path, content)

    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.atomic_write_text", side_effect=_record),
    ):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    assert written[-1] == "config.nu"


def test_deploy_force_redeploys_unchanged(tmp_project: Path, capsys):
    """--force should redeploy even when content is unchanged."""
    config_dir = tmp_project / "deploy_version_force"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project, force=True)

    output = capsys.readouterr().out
    assert "unchanged" in output


def test_deploy_shows_version_change(tmp_project: Path, capsys):
    """When version changes between deploys, should show old -> new."""
    config_dir = tmp_project / "deploy_version_change"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    config_path = config_dir / "config.nu"
    content = config_path.read_text(encoding="utf-8")
    content = content.replace(
        _get_version(tmp_project),
        "2020-01-01 00:00:00 +0000",
    )
    config_path.write_text(content, encoding="utf-8")

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project, force=True)

    output = capsys.readouterr().out
    assert "2020-01-01 00:00:00 +0000" in output
    assert "->" in output


def test_deploy_nushell_omp_success(tmp_project: Path):
    """When oh-my-posh is available, _deploy_nushell generates its init file."""
    config_dir = tmp_project / "nu-omp-test"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "oh-my-posh"

    # Include the problematic patterns that oh-my-posh (>= 30) actually emits
    omp_raw = (
        "# omp init output\n"
        "    mut execution_time = -1\n"
        "    # initial `$env.CMD_DURATION_MS` is `0823`\n"
        "    if $env.CMD_DURATION_MS != '0823' {\n"
        "        $execution_time = $env.CMD_DURATION_MS\n"
        "    }\n"
        "    let legacy = match $env.CMD_DURATION_MS { '0823' => -1, _ => 0 }\n"
        "            --save-cache\n"
        '            $"--no-status=($no_status)"\n'
        "    ^$_omp_executable print secondary\n"
        "    $clear = (history | is-empty) or "
        '((history | last 1 | get 0.command) == "clear")\n'
    )

    captured_cmds = []

    def _run_dispatch(cmd, **kwargs):
        captured_cmds.append(list(cmd))
        if _resolved_tool_name(cmd) == "oh-my-posh":
            return subprocess.CompletedProcess(args=cmd, returncode=0, stdout=omp_raw, stderr="")
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/oh-my-posh" if t == "oh-my-posh" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project)

    assert (config_dir / "oh-my-posh.nu").exists()
    omp_content = (config_dir / "oh-my-posh.nu").read_text(encoding="utf-8")
    assert "omp init output" in omp_content
    # Vendor autoload guard should be prepended
    assert "vendor" in omp_content
    assert "oh-my-posh.nu" in omp_content
    assert "path exists" in omp_content
    assert "rm $_vendor_omp" in omp_content
    # Guard should come BEFORE the init output
    guard_pos = omp_content.index("vendor")
    init_pos = omp_content.index("omp init output")
    assert guard_pos < init_pos, "vendor guard should be prepended before init output"
    # CMD_DURATION_MS should use null-safe accessor
    assert "default 823 | into int" in omp_content
    assert "let _history = (history | last 1)" in omp_content
    assert "$clear = if (($_history | length) == 0)" in omp_content
    assert "$clear = (history | is-empty) or" not in omp_content
    assert 'match ($env.CMD_DURATION_MS? | default "0823") {' in omp_content
    assert "if $env.CMD_DURATION_MS" not in omp_content
    assert "$execution_time = $env.CMD_DURATION_MS" not in omp_content
    assert "--no-status" not in omp_content
    # The --config injection should land after --save-cache
    assert omp_content.count("--config=") >= 2
    # The command should include --print flag
    omp_cmds = [c for c in captured_cmds if _resolved_tool_name(c) == "oh-my-posh"]
    assert any("--print" in c for c in omp_cmds), "oh-my-posh init should use --print"
    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "LAYER 1" in config_content
    assert "LAYER 2" in config_content
    assert "LAYER 3" in config_content
    assert "$env.MY_SHELL_VERSION = '2025-01-01 12:00:00 +0000'" in config_content


def test_global_nushell_verification_rejects_runtime_failure(tmp_project: Path):
    from core.doctor import CheckResult
    from core.merge import _verify_global_nushell_runtime

    failed = CheckResult("nushell runtime PATH", "fail", "prompt crashed")
    with (
        patch("core.doctor._check_nushell_runtime", return_value=failed),
        patch("core.doctor._check_nushell_prompt_contract", return_value=[]),
        pytest.raises(RuntimeError, match="prompt crashed"),
    ):
        _verify_global_nushell_runtime(tmp_project, tmp_project / "nu")


def test_failed_verification_does_not_leave_an_up_to_date_hash(tmp_project: Path):
    """A deploy that fails verification must re-deploy next run, not report Up to date."""
    from core.doctor import CheckResult
    from core.merge import _get_deployed_hash, deploy

    config_dir = tmp_project / "nu-verify-fail"
    config_dir.mkdir()
    failed = CheckResult("nushell runtime PATH", "fail", "prompt crashed")

    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.get_config_dir", return_value=config_dir),
        patch("core.doctor._check_nushell_runtime", return_value=failed),
        patch("core.doctor._check_nushell_prompt_contract", return_value=[]),
        pytest.raises(RuntimeError, match="prompt crashed"),
    ):
        deploy("nushell", project_dir=tmp_project)

    assert (config_dir / "config.nu").exists()
    assert not _get_deployed_hash("nushell", config_dir)


def test_deploy_nushell_omp_mise_installs_path_rewritten_to_shim(tmp_project: Path, monkeypatch):
    """oh-my-posh init bakes the exe path it was invoked as. A mise installs
    path contains the version dir, so every omp upgrade kills the prompt until
    a redeploy. The shim path never moves -- the deploy rewrites to it."""
    config_dir = tmp_project / "nu-omp-shim"
    config_dir.mkdir()
    shims = tmp_project / "mise-data" / "shims"
    shims.mkdir(parents=True)
    (shims / "oh-my-posh.exe").touch()
    monkeypatch.setenv("MISE_DATA_DIR", str(tmp_project / "mise-data"))

    def _avail(tool):
        return tool == "oh-my-posh"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "oh-my-posh":
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=0,
                stdout=(
                    'let _omp_executable: string = (echo "C:/u/mise/installs/'
                    'aqua-jan-de-dobbeleer-oh-my-posh/30.2.0/oh-my-posh.EXE")\n'
                ),
                stderr="",
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch("core.mise.shutil.which", return_value=None),
    ):
        _deploy_nushell(config_dir, tmp_project)

    content = (config_dir / "oh-my-posh.nu").read_text(encoding="utf-8")
    assert "/installs/" not in content
    assert (shims / "oh-my-posh.exe").as_posix() in content


def test_deploy_nushell_omp_non_mise_exe_path_untouched(tmp_project: Path, monkeypatch):
    """An omp exe outside mise installs has no version dir; leave it alone."""
    config_dir = tmp_project / "nu-omp-noshim"
    config_dir.mkdir()
    monkeypatch.setenv("MISE_DATA_DIR", str(tmp_project / "mise-data"))

    def _avail(tool):
        return tool == "oh-my-posh"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "oh-my-posh":
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=0,
                stdout=(
                    'let _omp_executable: string = (echo "C:/Program Files/'
                    'oh-my-posh/bin/oh-my-posh.exe")\n'
                ),
                stderr="",
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch("core.mise.shutil.which", return_value=None),
    ):
        _deploy_nushell(config_dir, tmp_project)

    content = (config_dir / "oh-my-posh.nu").read_text(encoding="utf-8")
    assert "C:/Program Files/oh-my-posh/bin/oh-my-posh.exe" in content


def test_deploy_nushell_omp_removes_vendor_autoload(tmp_project: Path):
    """_deploy_nushell should remove vendor/autoload/oh-my-posh.nu if it exists."""
    config_dir = tmp_project / "nu-omp-vendor"
    config_dir.mkdir()

    # Create a fake vendor/autoload/oh-my-posh.nu (simulates oh-my-posh 29.x behavior)
    vendor_dir = config_dir / "vendor" / "autoload"
    vendor_dir.mkdir(parents=True)
    vendor_omp = vendor_dir / "oh-my-posh.nu"
    vendor_omp.write_text("# buggy unpatched oh-my-posh init\n", encoding="utf-8")

    def _avail(tool):
        return tool == "oh-my-posh"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "oh-my-posh":
            return subprocess.CompletedProcess(
                args=cmd, returncode=0, stdout="# omp init\n", stderr=""
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/oh-my-posh" if t == "oh-my-posh" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project)

    # vendor/autoload/oh-my-posh.nu should be removed
    assert not vendor_omp.exists(), "vendor/autoload/oh-my-posh.nu should be removed"


def test_deploy_nushell_omp_error(tmp_project: Path):
    """When oh-my-posh subprocess fails, error is logged but deploy continues."""
    config_dir = tmp_project / "nu-omp-err"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "oh-my-posh"

    def _run_side_effect(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "oh-my-posh":
            raise subprocess.CalledProcessError(1, "oh-my-posh")
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_side_effect),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/oh-my-posh" if t == "oh-my-posh" else None,
        ),
        patch("core.merge.log_warn") as mock_warn,
    ):
        _deploy_nushell(config_dir, tmp_project)

    assert any("oh-my-posh" in str(c) for c in mock_warn.call_args_list)
    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "LAYER 1" in config_content
    assert "$env.MY_SHELL_VERSION" in config_content


def test_deploy_nushell_zoxide_success(tmp_project: Path):
    """When zoxide is available, _deploy_nushell generates its init file."""
    config_dir = tmp_project / "nu-zoxide-test"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "zoxide"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "zoxide":
            return subprocess.CompletedProcess(
                args=cmd, returncode=0, stdout="# zoxide init output\n", stderr=""
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    captured_cmd = []

    def _run_capture(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "zoxide":
            captured_cmd.extend(cmd)
        return _run_dispatch(cmd, **kwargs)

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_capture),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/zoxide" if t == "zoxide" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project)

    assert (config_dir / "zoxide.nu").exists()
    zoxide_content = (config_dir / "zoxide.nu").read_text(encoding="utf-8")
    assert "zoxide init output" in zoxide_content
    assert "alias cd = __zoxide_z" in zoxide_content
    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "LAYER 1" in config_content
    assert "LAYER 2" in config_content
    assert "LAYER 3" in config_content
    assert "$env.MY_SHELL_VERSION = '2025-01-01 12:00:00 +0000'" in config_content


def test_deploy_nushell_zoxide_error(tmp_project: Path):
    """When zoxide subprocess fails, error is logged but deploy continues."""
    config_dir = tmp_project / "nu-zoxide-err"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "zoxide"

    def _run_side_effect(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "zoxide":
            raise subprocess.CalledProcessError(1, "zoxide")
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_side_effect),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/zoxide" if t == "zoxide" else None,
        ),
        patch("core.merge.log_warn") as mock_warn,
    ):
        _deploy_nushell(config_dir, tmp_project)

    assert any("zoxide" in str(c) for c in mock_warn.call_args_list)
    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "LAYER 1" in config_content
    assert "$env.MY_SHELL_VERSION" in config_content


def test_deploy_nushell_omp_uses_configured_theme(tmp_project: Path):
    """Nushell deploy should pass the configured theme to oh-my-posh init."""
    (tmp_project / "config" / "settings.toml").write_text(
        '[oh-my-posh]\ntheme = "catppuccin"\n',
        encoding="utf-8",
    )
    themes_dir = tmp_project / "shells" / "shared" / "oh-my-posh" / "themes"
    (themes_dir / "catppuccin.omp.json").write_text("{}", encoding="utf-8")

    config_dir = tmp_project / "nu-omp-theme"
    config_dir.mkdir()

    captured_cmd = []

    def _avail(tool):
        return tool == "oh-my-posh"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "oh-my-posh":
            captured_cmd.extend(cmd)
            return subprocess.CompletedProcess(args=cmd, returncode=0, stdout="# omp\n", stderr="")
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/oh-my-posh" if t == "oh-my-posh" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project)

    assert any("catppuccin" in str(arg) for arg in captured_cmd)


def test_deploy_nushell_omp_injects_config_into_print(tmp_project: Path):
    """Generated oh-my-posh.nu must include --config in print commands
    so the theme survives cache invalidation (e.g. oh-my-posh upgrade)."""
    (tmp_project / "config" / "settings.toml").write_text(
        '[oh-my-posh]\ntheme = "dracula"\n',
        encoding="utf-8",
    )
    config_dir = tmp_project / "nu-omp-config-inject"
    config_dir.mkdir()

    # Simulate oh-my-posh init output (v29-style with --save-cache)
    fake_init = (
        "$env.POSH_SESSION_ID = 'test'\n"
        "def _omp_get_prompt [] {\n"
        "    ^$_omp_executable print $type\n"
        "        --save-cache\n"
        "        --shell=nu\n"
        "}\n"
        "$env.PROMPT_MULTILINE_INDICATOR = (\n"
        "    ^$_omp_executable print secondary\n"
        "        --shell=nu\n"
        ")\n"
    )

    def _avail(tool):
        return tool == "oh-my-posh"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "oh-my-posh":
            return subprocess.CompletedProcess(args=cmd, returncode=0, stdout=fake_init, stderr="")
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/oh-my-posh" if t == "oh-my-posh" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project)

    omp_content = (config_dir / "oh-my-posh.nu").read_text(encoding="utf-8")
    # --config must appear in both the _omp_get_prompt function and the secondary prompt
    assert '"--config=dracula"' in omp_content
    assert omp_content.count('"--config=dracula"') >= 2
    assert "--no-status" not in omp_content


def test_deploy_nushell_atuin_success(tmp_project: Path):
    """When atuin is available, _deploy_nushell generates its init file."""
    config_dir = tmp_project / "nu-atuin-test"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "atuin"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "atuin":
            return subprocess.CompletedProcess(
                args=cmd, returncode=0, stdout="# atuin init output\n", stderr=""
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/atuin" if t == "atuin" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project)

    assert (config_dir / "atuin.nu").exists()
    assert "atuin init output" in (config_dir / "atuin.nu").read_text(encoding="utf-8")


def _guard_dispatch(tool: str, tool_stdout: str, ide_stdout: str):
    """Build a subprocess.run side-effect: `tool` returns tool_stdout, `nu --ide-check`
    returns ide_stdout, anything else returns empty."""

    def _run(cmd, **kwargs):
        name = _resolved_tool_name(cmd)
        if name == tool:
            return subprocess.CompletedProcess(
                args=cmd, returncode=0, stdout=tool_stdout, stderr=""
            )
        if name == "nu":  # the --ide-check parse pass
            return subprocess.CompletedProcess(args=cmd, returncode=0, stdout=ide_stdout, stderr="")
        return subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    return _run


def test_ensure_nushell_tool_init_stubs_on_parse_error(tmp_path: Path):
    """A generated init that parses with errors gets replaced by a safe stub."""
    out = tmp_path / "atuin.nu"

    with (
        patch("core.merge.is_available", side_effect=lambda t: t in ("atuin", "nu")),
        patch(
            "core.merge.subprocess.run",
            side_effect=_guard_dispatch(
                "atuin",
                "job spawn -t atuin { true } | ignore\n",
                '[{"severity":"Error","message":"The `job spawn` command doesn\'t have flag `-t`."}]',
            ),
        ),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: f"/usr/bin/{t}" if t in ("atuin", "nu") else None,
        ),
        patch("core.merge.log_warn") as mock_warn,
    ):
        ok = _ensure_nushell_tool_init("atuin", ["atuin", "init", "nu"], out)

    assert ok is False
    content = out.read_text(encoding="utf-8")
    assert "Generated by my-shell" in content
    assert "job spawn" not in content  # broken output gone, replaced by stub
    assert any("parse errors" in str(c) for c in mock_warn.call_args_list)


def test_ensure_nushell_tool_init_keeps_valid_output(tmp_path: Path):
    """A generated init that parses clean is kept as-is."""
    out = tmp_path / "zoxide.nu"

    with (
        patch("core.merge.is_available", side_effect=lambda t: t in ("zoxide", "nu")),
        patch(
            "core.merge.subprocess.run",
            side_effect=_guard_dispatch("zoxide", "# zoxide ok\n", "[]"),
        ),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: f"/usr/bin/{t}" if t in ("zoxide", "nu") else None,
        ),
    ):
        ok = _ensure_nushell_tool_init("zoxide", ["zoxide", "init", "nushell"], out)

    assert ok is True
    assert "# zoxide ok" in out.read_text(encoding="utf-8")


def test_nushell_init_has_errors_skips_when_nu_missing(tmp_path: Path):
    """No nushell binary -> cannot validate -> never discard the file."""
    out = tmp_path / "x.nu"
    out.write_text("job spawn -t atuin {}", encoding="utf-8")
    with patch("core.merge.is_available", return_value=False):
        assert _nushell_init_has_errors(out) is False


def test_nushell_init_has_errors_fails_open_on_exception(tmp_path: Path):
    """If the parse check itself blows up, fail open (return False)."""
    out = tmp_path / "x.nu"
    out.write_text("whatever", encoding="utf-8")
    with (
        patch("core.merge.is_available", side_effect=lambda t: t == "nu"),
        patch("core.merge.subprocess.run", side_effect=OSError("boom")),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/nu" if t == "nu" else None,
        ),
    ):
        assert _nushell_init_has_errors(out) is False


def test_deploy_nushell_atuin_error(tmp_project: Path):
    """When atuin subprocess fails, error is logged but deploy continues."""
    config_dir = tmp_project / "nu-atuin-err"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "atuin"

    def _run_side_effect(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "atuin":
            raise subprocess.CalledProcessError(1, "atuin")
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_side_effect),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/atuin" if t == "atuin" else None,
        ),
        patch("core.merge.log_warn") as mock_warn,
    ):
        _deploy_nushell(config_dir, tmp_project)

    assert any("atuin" in str(c) for c in mock_warn.call_args_list)
    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "LAYER 1" in config_content
    assert "$env.MY_SHELL_VERSION" in config_content


def test_deploy_nushell_carapace_success(tmp_project: Path):
    """When carapace is available, _deploy_nushell generates its init file."""
    config_dir = tmp_project / "nu-carapace-test"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "carapace"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "carapace":
            return subprocess.CompletedProcess(
                args=cmd, returncode=0, stdout="# carapace init output\n", stderr=""
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/carapace" if t == "carapace" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project)

    assert (config_dir / "carapace.nu").exists()
    assert "carapace init output" in (config_dir / "carapace.nu").read_text(encoding="utf-8")


def test_deploy_nushell_carapace_error(tmp_project: Path):
    """When carapace subprocess fails, error is logged but deploy continues."""
    config_dir = tmp_project / "nu-carapace-err"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "carapace"

    def _run_side_effect(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "carapace":
            raise subprocess.CalledProcessError(1, "carapace")
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_side_effect),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/carapace" if t == "carapace" else None,
        ),
        patch("core.merge.log_warn") as mock_warn,
    ):
        _deploy_nushell(config_dir, tmp_project)

    assert any("carapace" in str(c) for c in mock_warn.call_args_list)
    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "LAYER 1" in config_content
    assert "$env.MY_SHELL_VERSION" in config_content


@pytest.mark.parametrize("tool", ["carapace", "atuin"])
def test_deploy_xonsh_preserves_integration_init(tmp_project: Path, tool: str):
    """Deploy must NOT overwrite a hand-crafted <tool>/init.xsh."""
    config_dir = tmp_project / f"deploy_test_xonsh_{tool}"
    fake_home = tmp_project / f"fake_home_{tool}"
    fake_home.mkdir()

    init_file = tmp_project / "shells" / "xonsh" / "integrations" / tool / "init.xsh"
    original_content = init_file.read_text(encoding="utf-8")

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.get_home_dir", return_value=fake_home),
        patch("core.merge._find_xonsh_python", return_value=None),
    ):
        deploy("xonsh", config_dir=config_dir, project_dir=tmp_project)

    assert init_file.read_text(encoding="utf-8") == original_content


def test_deploy_nushell_atuin_up_binding_gets_a_unique_name(tmp_project: Path):
    """atuin names both bindings "atuin"; nu warns on the shared name and drops one."""
    config_dir = tmp_project / "nu-atuin-test"
    config_dir.mkdir()

    atuin_init = (
        "$env.config = (\n"
        "    $env.config | upsert keybindings (\n"
        "        $env.config.keybindings\n"
        "        | append {\n"
        "            name: atuin\n"
        "            modifier: control\n"
        "            keycode: char_r\n"
        "            mode: [emacs, vi_normal, vi_insert]\n"
        '            event: { send: executehostcommand cmd: (_atuin_search_cmd "") }\n'
        "        }\n"
        "        | append {\n"
        "            name: atuin\n"
        "            modifier: none\n"
        "            keycode: up\n"
        "            mode: [emacs, vi_normal, vi_insert]\n"
        "            event: {\n"
        "                until: [\n"
        "                    {send: menuup}\n"
        "                    {send: executehostcommand cmd: "
        "(_atuin_search_cmd '--shell-up-key-binding') }\n"
        "                ]\n"
        "            }\n"
        "        }\n"
        "    )\n"
        ")\n"
    )

    def _avail(tool):
        return tool == "atuin"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "atuin":
            return subprocess.CompletedProcess(args=cmd, returncode=0, stdout=atuin_init, stderr="")
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch("core.mise.shutil.which", return_value=None),
    ):
        _deploy_nushell(config_dir, tmp_project)

    content = (config_dir / "atuin.nu").read_text(encoding="utf-8")
    assert "name: atuin_up" in content
    assert content.count("name: atuin\n") == 1


def test_deploy_nushell_mise_success(tmp_project: Path):
    """When mise is available, _deploy_nushell generates its init file."""
    config_dir = tmp_project / "nu-mise-test"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "mise"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "mise":
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=0,
                stdout=(
                    "def --env update-env [] {\n"
                    "  if ($var.name | str upcase) == 'PATH' {}\n"
                    "}\n"
                    "export-env {\n"
                    "  let mise_hook = {\n"
                    '    condition: { "MISE_SHELL" in $env }\n'
                    "    code: { mise_hook }\n"
                    "  }\n"
                    "  add-hook hooks.pre_prompt $mise_hook\n"
                    "  add-hook hooks.env_change.PWD $mise_hook\n"
                    "}\n"
                ),
                stderr="",
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/mise" if t == "mise" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project)

    content = (config_dir / "mise.nu").read_text(encoding="utf-8")
    assert "hooks.pre_prompt" not in content
    assert "hooks.env_change.PWD" in content
    assert "str upcase" not in content
    assert "str uppercase" in content


def test_strip_transient_path_entries_drops_venv_dirs(monkeypatch, tmp_path: Path):
    """PATH entries under the running venv must not leak into tool-init subprocesses."""
    import sys

    from core.merge import _strip_transient_path_entries

    venv = tmp_path / ".venv"
    monkeypatch.setattr(sys, "prefix", str(venv))
    monkeypatch.setattr(sys, "base_prefix", str(tmp_path / "base-py"))
    monkeypatch.setenv("VIRTUAL_ENV", str(venv))

    keep_a = str(tmp_path / "tools" / "bin")
    keep_b = str(tmp_path / "other")
    path = os.pathsep.join([str(venv / "Scripts"), keep_a, str(venv / "bin"), keep_b])
    assert _strip_transient_path_entries(path) == os.pathsep.join([keep_a, keep_b])


def test_strip_transient_path_entries_no_venv_keeps_base_python(monkeypatch, tmp_path: Path):
    """Outside a venv, sys.prefix is the base install -- never strip it."""
    import sys

    from core.merge import _strip_transient_path_entries

    base = str(tmp_path / "base-py")
    monkeypatch.setattr(sys, "prefix", base)
    monkeypatch.setattr(sys, "base_prefix", base)
    monkeypatch.delenv("VIRTUAL_ENV", raising=False)

    path = os.pathsep.join([str(tmp_path / "base-py" / "Scripts"), str(tmp_path / "tools")])
    assert _strip_transient_path_entries(path) == path


def test_render_tool_init_subprocess_gets_sanitized_path(
    tmp_project: Path, monkeypatch, tmp_path: Path
):
    """The env handed to a tool's init subprocess must not contain venv PATH entries,
    so generated configs (which bake the subprocess PATH) stay clean."""
    import sys

    from core.merge import _render_tool_init

    venv = str(tmp_path / ".venv")
    monkeypatch.setattr(sys, "prefix", venv)
    monkeypatch.setattr(sys, "base_prefix", str(tmp_path / "base-py"))
    monkeypatch.setenv("VIRTUAL_ENV", venv)
    monkeypatch.setenv(
        "PATH",
        os.pathsep.join([str(Path(venv) / "Scripts"), str(tmp_path / "tools" / "bin")]),
    )

    seen_env: dict = {}

    def _run_capture(cmd, **kwargs):
        seen_env.update(kwargs.get("env") or {})
        return subprocess.CompletedProcess(args=cmd, returncode=0, stdout="init\n", stderr="")

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run", side_effect=_run_capture),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/mise" if t == "mise" else None,
        ),
    ):
        out = _render_tool_init("mise", ["mise", "activate", "nu"], project_dir=tmp_project)

    assert out is not None
    path_key = next(k for k in seen_env if k.upper() == "PATH")
    assert str(Path(venv) / "Scripts") not in seen_env[path_key]
    assert str(tmp_path / "tools" / "bin") in seen_env[path_key]


def test_deploy_nushell_mise_string_path_normalized(tmp_project: Path):
    """mise >= 2026.7 emits `$env.PATH = r#'...'#` -- a deploy-day PATH snapshot
    assigned as one raw string.

    Two defenses must both land in the deployed init: the baked snapshot line is
    stripped (the inherited PATH plus the shims re-add covers startup), and the
    string-PATH split guard is appended for any other string assignment.
    """
    config_dir = tmp_project / "nu-mise-strpath"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "mise"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "mise":
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=0,
                stdout=(
                    "export-env {\n"
                    "  $env.PATH = r#'C:\\a;C:\\b'#\n"
                    "  add-hook hooks.env_change.PWD $mise_hook\n"
                    "}\n"
                ),
                stderr="",
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/mise" if t == "mise" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project)

    content = (config_dir / "mise.nu").read_text(encoding="utf-8")
    assert "r#'C:\\a;C:\\b'#" not in content
    assert "split row (char esep)" in content


def test_deploy_nushell_mise_csv_path_stripped(tmp_project: Path):
    """mise >= 2026.8 bakes the deploy-day PATH as a `set,PATH,...` CSV row
    piped through `parse vars | update-env` instead of a raw-string assignment.

    The PATH row must be stripped (shims + the startup env_change.PWD hook cover
    startup); the hide rows and the rest of the CSV must survive.
    """
    config_dir = tmp_project / "nu-mise-csvpath"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "mise"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "mise":
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=0,
                stdout=(
                    "export-env {\n"
                    "  \n"
                    "  'set,PATH,C:\\a;C:\\b\n"
                    "hide,MISE_SHELL,\n"
                    "hide,__MISE_DIFF,' | parse vars | update-env\n"
                    "  add-hook hooks.env_change.PWD $mise_hook\n"
                    "}\n"
                ),
                stderr="",
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/mise" if t == "mise" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project)

    content = (config_dir / "mise.nu").read_text(encoding="utf-8")
    assert "set,PATH," not in content
    assert "'hide,MISE_SHELL,\nhide,__MISE_DIFF,' | parse vars | update-env" in content


def test_deploy_nushell_post_process_miss_lands_in_warnings(tmp_project: Path):
    """A post_process pattern that no longer matches must surface as a deploy
    warning, not just a scrolled log line."""
    config_dir = tmp_project / "nu-mise-ppmiss"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "mise"

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "mise":
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=0,
                stdout="export-env {\n  # format changed, no pre_prompt hook line\n}\n",
                stderr="",
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    warnings: list[str] = []
    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/mise" if t == "mise" else None,
        ),
    ):
        _deploy_nushell(config_dir, tmp_project, warnings=warnings)

    assert any("mise" in w for w in warnings)


def test_render_tool_init_file_not_found_returns_none(tmp_project: Path):
    """A tool vanishing between is_available and the init run must not raise."""
    from core.merge import _render_tool_init

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run", side_effect=FileNotFoundError("gone")),
        patch("core.mise.shutil.which", return_value=None),
    ):
        assert _render_tool_init("zoxide", ["zoxide", "init", "nushell"]) is None


def test_mise_shims_block_honors_mise_data_dir():
    from core.merge import _render_nushell_mise_shims_block

    block = _render_nushell_mise_shims_block()
    assert "MISE_DATA_DIR" in block


def test_deploy_nushell_mise_error(tmp_project: Path):
    """When mise subprocess fails, error is logged but deploy continues."""
    config_dir = tmp_project / "nu-mise-err"
    config_dir.mkdir()

    def _avail(tool):
        return tool == "mise"

    def _run_side_effect(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "mise":
            raise subprocess.CalledProcessError(1, "mise")
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    with (
        patch("core.merge.is_available", side_effect=_avail),
        patch("core.merge.subprocess.run", side_effect=_run_side_effect),
        patch(
            "core.mise.shutil.which",
            side_effect=lambda t: "/usr/bin/mise" if t == "mise" else None,
        ),
        patch("core.merge.log_warn") as mock_warn,
    ):
        _deploy_nushell(config_dir, tmp_project)

    assert any("mise" in str(c) for c in mock_warn.call_args_list)
    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "LAYER 1" in config_content
    assert "$env.MY_SHELL_VERSION" in config_content


_GIT_OPT_IN = {"git": {"manage_global_config": True}}


def test_deploy_delta_gitconfig_success(tmp_path: Path):
    """With delta available and the opt-in set, git config commands are called."""
    with (
        patch("core.merge.load_settings", return_value=_GIT_OPT_IN),
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
    ):
        _deploy_delta_gitconfig(tmp_path)

    assert mock_run.call_count == 5
    cmds = [call.args[0] for call in mock_run.call_args_list]
    assert cmds[0] == ["git", "config", "--global", "core.pager", "delta"]
    assert cmds[4] == ["git", "config", "--global", "merge.conflictStyle", "zdiff3"]


def test_deploy_delta_gitconfig_not_available(tmp_path: Path):
    """When delta is not available, no git config commands should be called."""
    with (
        patch("core.merge.load_settings", return_value=_GIT_OPT_IN),
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.subprocess.run") as mock_run,
    ):
        _deploy_delta_gitconfig(tmp_path)

    mock_run.assert_not_called()


@pytest.mark.parametrize("settings", [{}, {"git": {}}, {"git": {"manage_global_config": False}}])
def test_deploy_delta_gitconfig_needs_opt_in(tmp_path: Path, settings: dict):
    """The global ~/.gitconfig is never touched without [git] manage_global_config."""
    with (
        patch("core.merge.load_settings", return_value=settings),
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
    ):
        _deploy_delta_gitconfig(tmp_path)

    mock_run.assert_not_called()


def test_deploy_delta_gitconfig_error(tmp_path: Path):
    """When git config fails, error is logged."""
    with (
        patch("core.merge.load_settings", return_value=_GIT_OPT_IN),
        patch("core.merge.is_available", return_value=True),
        patch(
            "core.merge.subprocess.run",
            side_effect=subprocess.CalledProcessError(1, "git"),
        ),
        patch("core.merge.log_error") as mock_err,
    ):
        _deploy_delta_gitconfig(tmp_path)

    assert mock_err.called
    assert any("delta" in str(c) for c in mock_err.call_args_list)


def test_render_tool_init_returns_processed_text_without_writing(tmp_path: Path):
    """_render_tool_init runs the init and returns processed text, writing nothing."""
    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
        patch("core.mise.shutil.which", return_value="/usr/bin/test"),
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["test", "init"], returncode=0, stdout="RAW\n", stderr=""
        )
        out = _render_tool_init(
            "test", ["test", "init"], post_process=[("RAW", "COOKED")], append_lines=["# end"]
        )
    assert out == "# Generated by my-shell\nCOOKED\n\n# end\n"
    assert list(tmp_path.iterdir()) == []  # pure: nothing written


def test_render_tool_init_none_when_unavailable():
    with patch("core.merge.is_available", return_value=False):
        assert _render_tool_init("test", ["test", "init"]) is None


def test_render_tool_init_warns_on_stale_post_process():
    """A post_process pattern that matches nothing warns -- a silent revert otherwise."""
    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
        patch("core.mise.shutil.which", return_value="/usr/bin/test"),
        patch("core.merge.log_warn") as mock_warn,
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["test", "init"], returncode=0, stdout="hello world\n", stderr=""
        )
        out = _render_tool_init("test", ["test", "init"], post_process=[("NOTPRESENT", "x")])
    assert out == "# Generated by my-shell\nhello world\n"  # unchanged (pattern not found)
    assert any("post-process pattern not found" in str(c) for c in mock_warn.call_args_list)


def test_render_tool_init_no_warn_when_pattern_matches():
    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
        patch("core.mise.shutil.which", return_value="/usr/bin/test"),
        patch("core.merge.log_warn") as mock_warn,
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["test", "init"], returncode=0, stdout="hello\n", stderr=""
        )
        out = _render_tool_init("test", ["test", "init"], post_process=[("hello", "hi")])
    assert out == "# Generated by my-shell\nhi\n"
    assert not mock_warn.called


def test_nushell_tool_init_specs_only_enabled():
    """Specs are built only for enabled tools, with config_dir-relative paths."""
    cfg = Path("/cfg")
    with patch("core.merge.is_integration_enabled", side_effect=lambda s, n: n == "zoxide"):
        specs = _nushell_tool_init_specs(cfg, Path("/proj"), {})
    assert [s.tool_name for s in specs] == ["zoxide"]
    assert specs[0].output_path == cfg / "zoxide.nu"
    assert specs[0].cmd == ["zoxide", "init", "nushell"]


def test_nushell_tool_init_specs_returns_toolinitspec():
    with patch("core.merge.is_integration_enabled", side_effect=lambda s, n: n == "carapace"):
        specs = _nushell_tool_init_specs(Path("/cfg"), Path("/proj"), {})
    assert isinstance(specs[0], ToolInitSpec)
    assert specs[0].cmd == ["carapace", "_carapace", "nushell"]


def test_generate_tool_init_success(tmp_path: Path):
    """_generate_tool_init should write tool output to file."""
    output_path = tmp_path / "test.nu"

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
        patch("core.mise.shutil.which", return_value="/usr/bin/test"),
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["test", "init"], returncode=0, stdout="# init output\n", stderr=""
        )
        result = _generate_tool_init("test", ["test", "init"], output_path)

    assert result is True
    assert output_path.exists()
    assert "init output" in output_path.read_text(encoding="utf-8")


def test_generate_tool_init_drops_empty_xdg_config_home(tmp_path: Path):
    """Empty XDG_CONFIG_HOME must not make tools write config below the repo cwd."""
    output_path = tmp_path / "test.nu"
    completed = subprocess.CompletedProcess(
        args=["test", "init"], returncode=0, stdout="# init output\n", stderr=""
    )

    with (
        patch("core.merge.is_available", return_value=True),
        patch(
            "core.merge.resolve_command",
            return_value=CommandSpec(
                ["/usr/bin/test", "init"],
                cwd=tmp_path,
                env={"HOME": str(tmp_path), "XDG_CONFIG_HOME": "", "PATH": "/usr/bin"},
            ),
        ),
        patch("core.merge.subprocess.run", return_value=completed) as run,
    ):
        assert _generate_tool_init("test", ["test", "init"], output_path)

    assert "XDG_CONFIG_HOME" not in run.call_args.kwargs["env"]


def test_generate_tool_init_not_available(tmp_path: Path):
    """_generate_tool_init should return False when tool is not available."""
    output_path = tmp_path / "test.nu"

    with patch("core.merge.is_available", return_value=False):
        result = _generate_tool_init("test", ["test", "init"], output_path)

    assert result is False
    assert not output_path.exists()


def test_generate_tool_init_timeout(tmp_path: Path):
    """_generate_tool_init should handle timeout gracefully."""
    output_path = tmp_path / "test.nu"

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run", side_effect=subprocess.TimeoutExpired("test", 30)),
        patch("core.mise.shutil.which", return_value="/usr/bin/test"),
        patch("core.merge.log_error") as mock_err,
    ):
        result = _generate_tool_init("test", ["test", "init"], output_path, timeout=30)

    assert result is False
    assert mock_err.called
    assert any("timed out" in str(c) for c in mock_err.call_args_list)


def test_generate_tool_init_post_process(tmp_path: Path):
    """_generate_tool_init should apply post_process replacement."""
    output_path = tmp_path / "test.nu"

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
        patch("core.mise.shutil.which", return_value="/usr/bin/test"),
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["test", "init"], returncode=0, stdout="old pattern here\n", stderr=""
        )
        result = _generate_tool_init(
            "test",
            ["test", "init"],
            output_path,
            post_process=[("old pattern", "new pattern")],
        )

    assert result is True
    content = output_path.read_text(encoding="utf-8")
    assert "new pattern" in content
    assert "old pattern" not in content


def test_generate_tool_init_post_process_multiple(tmp_path: Path):
    """_generate_tool_init should apply multiple post_process replacements."""
    output_path = tmp_path / "test.nu"

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
        patch("core.mise.shutil.which", return_value="/usr/bin/test"),
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["test", "init"],
            returncode=0,
            stdout="alpha and beta here\n",
            stderr="",
        )
        result = _generate_tool_init(
            "test",
            ["test", "init"],
            output_path,
            post_process=[("alpha", "ALPHA"), ("beta", "BETA")],
        )

    assert result is True
    content = output_path.read_text(encoding="utf-8")
    assert "ALPHA" in content
    assert "BETA" in content
    assert "alpha" not in content
    assert "beta" not in content


def test_generate_tool_init_append_lines(tmp_path: Path):
    """_generate_tool_init should append extra lines."""
    output_path = tmp_path / "test.nu"

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
        patch("core.mise.shutil.which", return_value="/usr/bin/test"),
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["test", "init"], returncode=0, stdout="# init\n", stderr=""
        )
        result = _generate_tool_init(
            "test",
            ["test", "init"],
            output_path,
            append_lines=["# extra line 1", "# extra line 2"],
        )

    assert result is True
    content = output_path.read_text(encoding="utf-8")
    assert "extra line 1" in content
    assert "extra line 2" in content


def test_generate_tool_init_prepend_lines(tmp_path: Path):
    """_generate_tool_init should prepend extra lines before tool output."""
    output_path = tmp_path / "test.nu"

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
        patch("core.mise.shutil.which", return_value="/usr/bin/test"),
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["test", "init"], returncode=0, stdout="# init output\n", stderr=""
        )
        result = _generate_tool_init(
            "test",
            ["test", "init"],
            output_path,
            prepend_lines=["# guard line 1", "# guard line 2"],
        )

    assert result is True
    content = output_path.read_text(encoding="utf-8")
    assert "guard line 1" in content
    assert "guard line 2" in content
    # Prepended lines should come before init output
    assert content.index("guard line 1") < content.index("init output")


def test_omp_guard_is_lightweight(tmp_path: Path):
    """The oh-my-posh vendor/autoload guard must be small and spawn no subprocesses."""
    output_path = tmp_path / "oh-my-posh.nu"

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.merge.subprocess.run") as mock_run,
        patch("core.mise.shutil.which", return_value="/usr/bin/oh-my-posh"),
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["oh-my-posh", "init"], returncode=0, stdout="# omp init output\n", stderr=""
        )
        _generate_tool_init(
            "oh-my-posh",
            ["oh-my-posh", "init", "nu", "--print", "--config", "theme.json"],
            output_path,
            prepend_lines=[
                "# my-shell: prevent double-init from standalone oh-my-posh vendor/autoload",
                'let _vendor_omp = ($nu.default-config-dir | path join "vendor" "autoload" "oh-my-posh.nu")',
                "if ($_vendor_omp | path exists) { rm $_vendor_omp }",
            ],
        )

    content = output_path.read_text(encoding="utf-8")
    # Guard = lines before the tool's init output
    guard_lines = content.split("# omp init output")[0].strip().splitlines()

    assert len(guard_lines) <= 5, f"Guard too large ({len(guard_lines)} lines): {guard_lines}"
    guard_text = "\n".join(guard_lines)
    assert "^" not in guard_text, "Guard must not spawn external commands (found '^')"
    for banned in ("http ", "fetch "):
        assert banned not in guard_text, f"Guard must not use network commands (found '{banned}')"


def test_generate_tool_init_subprocess_error(tmp_path: Path):
    """_generate_tool_init should handle subprocess failures gracefully."""
    output_path = tmp_path / "test.nu"

    with (
        patch("core.merge.is_available", return_value=True),
        patch(
            "core.merge.subprocess.run",
            side_effect=subprocess.CalledProcessError(1, "test"),
        ),
        patch("core.mise.shutil.which", return_value="/usr/bin/test"),
        patch("core.merge.log_warn") as mock_warn,
    ):
        result = _generate_tool_init("test", ["test", "init"], output_path)

    assert result is False
    assert mock_warn.called


def test_ensure_nushell_tool_init_writes_failure_stub(tmp_path: Path):
    """A failing Nushell tool init should leave a managed stub behind."""
    output_path = tmp_path / "atuin.nu"

    with (
        patch("core.merge.is_available", return_value=True),
        patch(
            "core.merge.subprocess.run",
            side_effect=subprocess.CalledProcessError(1, "atuin", stderr="boom"),
        ),
        patch("core.mise.shutil.which", return_value="/usr/bin/atuin"),
    ):
        result = _ensure_nushell_tool_init("atuin", ["atuin", "init", "nu"], output_path)

    assert result is False
    content = output_path.read_text(encoding="utf-8")
    assert "Generated by my-shell" in content
    assert "init failed during deploy" in content


def test_get_version_timeout():
    """_get_version should return 'unknown' on timeout."""
    with patch(
        "core.merge.subprocess.run",
        side_effect=subprocess.TimeoutExpired("git", 10),
    ):
        assert _get_version(Path("/nonexistent")) == "unknown"


def test_resolve_cmd_tool_in_path():
    """When tool is directly in PATH, resolve_command returns cmd unchanged."""
    cmd = ["oh-my-posh", "init", "nu"]
    with patch(
        "core.mise.shutil.which",
        side_effect=lambda tool: "/usr/bin/oh-my-posh" if tool == "oh-my-posh" else None,
    ):
        result = resolve_command(cmd)

    assert Path(result.args[0]) == Path("/usr/bin/oh-my-posh")
    assert result.args[1:] == ["init", "nu"]
    assert result.cwd is None
    assert result.env is None


def test_resolve_cmd_tool_via_mise():
    """When tool is NOT in PATH but mise knows it, run the resolved binary."""
    cmd = ["oh-my-posh", "init", "nu"]

    def _which(tool):
        if tool == "mise":
            return "/usr/bin/mise"
        return None

    with (
        patch("core.mise.shutil.which", side_effect=_which),
        patch("core.mise.subprocess.run") as mock_run,
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["mise", "which", "oh-my-posh"],
            returncode=0,
            stdout="/home/user/.local/share/mise/installs/oh-my-posh/latest/bin/oh-my-posh\n",
            stderr="",
        )
        result = resolve_command(cmd, project_dir=Path("/tmp/my-shell"))

    assert Path(result.args[0]) == Path(
        "/home/user/.local/share/mise/installs/oh-my-posh/latest/bin/oh-my-posh"
    )
    assert result.args[1:] == ["init", "nu"]
    assert result.cwd == Path("/tmp/my-shell")
    assert str(Path("/tmp/my-shell")) in result.env["MISE_TRUSTED_CONFIG_PATHS"]


def test_resolve_cmd_mise_managed_wins_over_stray_path_binary():
    """A same-named binary elsewhere on PATH (Homebrew, apt) must not shadow
    the version this project pins and tests against via mise."""
    cmd = ["oh-my-posh", "init", "nu"]

    def _which(tool):
        if tool == "mise":
            return "/usr/bin/mise"
        if tool == "oh-my-posh":
            return "/opt/homebrew/bin/oh-my-posh"
        return None

    with (
        patch("core.mise.shutil.which", side_effect=_which),
        patch("core.mise.subprocess.run") as mock_run,
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["mise", "which", "oh-my-posh"],
            returncode=0,
            stdout="/home/user/.local/share/mise/installs/oh-my-posh/pinned/bin/oh-my-posh\n",
            stderr="",
        )
        result = resolve_command(cmd, project_dir=Path("/tmp/my-shell"))

    assert Path(result.args[0]) == Path(
        "/home/user/.local/share/mise/installs/oh-my-posh/pinned/bin/oh-my-posh"
    )


def test_resolve_cmd_falls_back_to_path_when_mise_does_not_manage_tool():
    """A tool mise has no pin for still resolves via bare PATH."""
    cmd = ["git", "status"]

    def _which(tool):
        if tool == "mise":
            return "/usr/bin/mise"
        if tool == "git":
            return "/usr/bin/git"
        return None

    with (
        patch("core.mise.shutil.which", side_effect=_which),
        patch("core.mise.subprocess.run") as mock_run,
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["mise", "which", "git"], returncode=1, stdout="", stderr=""
        )
        result = resolve_command(cmd, project_dir=Path("/tmp/my-shell"))

    assert Path(result.args[0]) == Path("/usr/bin/git")


def test_resolve_cmd_tool_not_anywhere():
    """When tool is neither in PATH nor known to mise, return cmd unchanged."""
    cmd = ["oh-my-posh", "init", "nu"]

    def _which(tool):
        if tool == "mise":
            return "/usr/bin/mise"
        return None

    with (
        patch("core.mise.shutil.which", side_effect=_which),
        patch("core.mise.subprocess.run") as mock_run,
    ):
        mock_run.return_value = subprocess.CompletedProcess(
            args=["mise", "which", "oh-my-posh"],
            returncode=1,
            stdout="",
            stderr="",
        )
        result = resolve_command(cmd)

    assert result.args == cmd
    assert result.cwd is None
    assert result.env is None


def test_resolve_cmd_mise_shim_in_path_uses_trusted_env():
    """Direct mise shims in PATH still need a trusted env for repo commands."""
    cmd = ["oh-my-posh", "init", "nu"]
    shim = str(Path.home() / ".local" / "share" / "mise" / "shims" / "oh-my-posh")

    with patch("core.mise.shutil.which", return_value=shim):
        result = resolve_command(cmd, project_dir=Path("/tmp/my-shell"))

    assert result.args == [shim, "init", "nu"]
    assert result.cwd == Path("/tmp/my-shell")
    assert str(Path("/tmp/my-shell")) in result.env["MISE_TRUSTED_CONFIG_PATHS"]


def test_resolve_cmd_no_mise():
    """When neither tool nor mise is in PATH, return cmd unchanged."""
    cmd = ["oh-my-posh", "init", "nu"]

    with patch("core.mise.shutil.which", return_value=None):
        result = resolve_command(cmd)

    assert result.args == cmd
    assert result.cwd is None
    assert result.env is None


def test_deploy_result_integrations_all_available(tmp_project: Path):
    """DeployResult.integrations should have all 5 keys True when all tools available."""
    config_dir = tmp_project / "deploy_int_all"

    with patch("core.merge.is_available", return_value=True):
        result = deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    expected_tools = {"oh-my-posh", "zoxide", "atuin", "carapace", "mise"}
    assert set(result.integrations.keys()) >= expected_tools
    for tool in expected_tools:
        assert result.integrations[tool] is True, f"{tool} should be True"


def test_deploy_result_integrations_only_mise(tmp_project: Path):
    """DeployResult.integrations should reflect partial availability."""
    config_dir = tmp_project / "deploy_int_mise"

    def _avail(tool):
        return tool == "mise"

    with patch("core.merge.is_available", side_effect=_avail):
        result = deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    assert result.integrations["mise"] is True
    assert result.integrations["oh-my-posh"] is False
    assert result.integrations["zoxide"] is False
    assert result.integrations["atuin"] is False
    assert result.integrations["carapace"] is False


def test_deploy_summary_shows_all_integrations(tmp_project: Path, capsys):
    """Post-deploy summary should list all integration names with + or - markers."""
    config_dir = tmp_project / "deploy_summary"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    output = capsys.readouterr().out
    for tool in ["oh-my-posh", "zoxide", "atuin", "carapace", "mise"]:
        assert tool in output, f"{tool} should appear in summary output"


def test_deploy_xonsh_summary_shows_dynamic_config_dir(tmp_project: Path, capsys):
    """xonsh deploy summary should show the actual config_dir, not a hardcoded path."""
    config_dir = tmp_project / "deploy_xonsh_summary"
    fake_home = tmp_project / "fake_home_summary"
    fake_home.mkdir()

    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.get_home_dir", return_value=fake_home),
        patch("core.merge._find_xonsh_python", return_value=None),
    ):
        deploy("xonsh", config_dir=config_dir, project_dir=tmp_project)

    output = capsys.readouterr().out
    # The "Customize:" line must use the actual config_dir, not a hardcoded path
    assert str(config_dir / "user-custom.xsh") in output
    assert "~/.config/xonsh" not in output


def test_deploy_nushell_config_includes_sysinfo(tmp_project: Path):
    """Deployed config.nu should source sysinfo.nu command module."""
    config_dir = tmp_project / "deploy_sysinfo"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert "sysinfo.nu" in config_content
    assert 'use "' in config_content  # uses 'use' statement for command modules


def test_template_editor_fallback_is_vi(real_project_dir: Path):
    """config.nu.template editor fallback must be 'vi', not 'notepad'."""
    template = real_project_dir / "shells" / "nushell" / "config.nu.template"
    content = template.read_text(encoding="utf-8")
    assert '"notepad"' not in content, "Editor fallback should not be 'notepad'"
    assert '"vi"' in content, "Editor fallback should be 'vi'"


def test_template_comments_no_hardcoded_config_path(real_project_dir: Path):
    """Template comments must not contain hardcoded ~/.config/nushell paths."""
    for name in ("config.nu.template", "env.nu.template"):
        template = real_project_dir / "shells" / "nushell" / name
        content = template.read_text(encoding="utf-8")
        assert "~/.config/nushell" not in content, f"{name} should not reference ~/.config/nushell"
        assert "nushell config directory" in content, (
            f"{name} should use generic 'nushell config directory' wording"
        )


def test_env_template_has_homebrew_path_block(real_project_dir: Path):
    """env.nu.template must include the Homebrew Apple Silicon PATH block."""
    template = real_project_dir / "shells" / "nushell" / "env.nu.template"
    content = template.read_text(encoding="utf-8")
    assert "/opt/homebrew/bin" in content, (
        "env.nu.template should add /opt/homebrew/bin for Apple Silicon"
    )
    assert 'if ($nu.os-info.name == "macos")' in content, (
        "Homebrew PATH block should be macOS-conditional"
    )


def test_env_template_homebrew_path_deduplicates(real_project_dir: Path):
    """env.nu.template Homebrew block must guard against PATH duplication."""
    template = real_project_dir / "shells" / "nushell" / "env.nu.template"
    content = template.read_text(encoding="utf-8")
    assert "not-in $env.PATH" in content, (
        "Homebrew PATH block should check 'not-in $env.PATH' to prevent duplicates"
    )


def test_generate_tool_init_uses_resolved_mise_binary(tmp_path: Path):
    """_generate_tool_init invokes the binary resolved through `mise which`."""
    output_path = tmp_path / "zoxide.nu"
    project_dir = tmp_path / "project"
    project_dir.mkdir()

    def _which(tool):
        if tool == "mise":
            return "/usr/bin/mise"
        return None  # zoxide not directly in PATH

    def _run_dispatch(cmd, **kwargs):
        # resolve_command probes mise for the tool path
        if Path(cmd[0]) == Path("/usr/bin/mise") and cmd[1:] == ["which", "zoxide"]:
            assert kwargs["cwd"] == project_dir
            assert str(project_dir) in kwargs["env"]["MISE_TRUSTED_CONFIG_PATHS"]
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=0,
                stdout="/home/user/.local/share/mise/installs/zoxide/latest/bin/zoxide\n",
                stderr="",
            )
        # _generate_tool_init runs the resolved binary directly
        if Path(cmd[0]) == Path(
            "/home/user/.local/share/mise/installs/zoxide/latest/bin/zoxide"
        ) and cmd[1:] == ["init", "nushell"]:
            assert kwargs["cwd"] == project_dir
            assert str(project_dir) in kwargs["env"]["MISE_TRUSTED_CONFIG_PATHS"]
            return subprocess.CompletedProcess(
                args=cmd, returncode=0, stdout="# zoxide init via mise\n", stderr=""
            )
        raise AssertionError(f"Unexpected subprocess call: {cmd}")

    with (
        patch("core.merge.is_available", return_value=True),
        patch("core.mise.shutil.which", side_effect=_which),
        patch("core.mise.subprocess.run", side_effect=_run_dispatch),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
    ):
        result = _generate_tool_init(
            "zoxide",
            ["zoxide", "init", "nushell"],
            output_path,
            project_dir=project_dir,
        )

    assert result is True
    assert output_path.exists()
    assert "zoxide init via mise" in output_path.read_text(encoding="utf-8")


def test_generated_config_comment_uses_config_dir(tmp_project: Path):
    """Deployed config.nu comment should reference the actual config_dir, not ~/.config/nushell."""
    config_dir = tmp_project / "custom_nu_config"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    config_content = (config_dir / "config.nu").read_text(encoding="utf-8")
    assert str(config_dir / "user-custom.nu") in config_content
    assert "~/.config/nushell" not in config_content


def test_generated_xonshrc_comment_uses_config_dir(tmp_project: Path):
    """Deployed xonshrc comment should reference the actual config_dir, not ~/.config/xonsh."""
    config_dir = tmp_project / "custom_xonsh_config"
    fake_home = tmp_project / "fake_home_comment"
    fake_home.mkdir()

    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.get_home_dir", return_value=fake_home),
        patch("core.merge._find_xonsh_python", return_value=None),
    ):
        deploy("xonsh", config_dir=config_dir, project_dir=tmp_project)

    xonshrc = (fake_home / ".xonshrc").read_text(encoding="utf-8")
    assert str(config_dir / "user-custom.xsh") in xonshrc
    assert "~/.config/xonsh" not in xonshrc


def test_warn_stale_config_macos_library_active(tmp_path: Path):
    """On macOS with Library active, warn if stale config exists at ~/.config."""
    home = tmp_path / "home"
    active_dir = home / "Library" / "Application Support" / "nushell"
    stale_dir = home / ".config" / "nushell"
    active_dir.mkdir(parents=True)
    stale_dir.mkdir(parents=True)
    (stale_dir / "config.nu").write_text("# stale", encoding="utf-8")

    with (
        patch("core.merge.get_os", return_value="macos"),
        patch("core.merge.get_home_dir", return_value=home),
        patch("core.merge.log_warn") as mock_warn,
    ):
        _warn_stale_config("nushell", active_dir)

    assert mock_warn.called
    msg = mock_warn.call_args[0][0]
    assert "Stale" in msg
    assert str(stale_dir) in msg


def test_warn_stale_config_macos_xdg_active(tmp_path: Path):
    """On macOS with .config active, warn if stale config exists at Library."""
    home = tmp_path / "home"
    active_dir = home / ".config" / "nushell"
    stale_dir = home / "Library" / "Application Support" / "nushell"
    active_dir.mkdir(parents=True)
    stale_dir.mkdir(parents=True)
    (stale_dir / "config.nu").write_text("# stale", encoding="utf-8")

    with (
        patch("core.merge.get_os", return_value="macos"),
        patch("core.merge.get_home_dir", return_value=home),
        patch("core.merge.log_warn") as mock_warn,
    ):
        _warn_stale_config("nushell", active_dir)

    assert mock_warn.called
    msg = mock_warn.call_args[0][0]
    assert "Stale" in msg
    assert str(stale_dir) in msg


def test_warn_stale_config_no_stale_file(tmp_path: Path):
    """No warning when the other location does not have a config file."""
    home = tmp_path / "home"
    active_dir = home / "Library" / "Application Support" / "nushell"
    stale_dir = home / ".config" / "nushell"
    active_dir.mkdir(parents=True)
    # stale_dir exists but has no config.nu
    stale_dir.mkdir(parents=True)

    with (
        patch("core.merge.get_os", return_value="macos"),
        patch("core.merge.get_home_dir", return_value=home),
        patch("core.merge.log_warn") as mock_warn,
    ):
        _warn_stale_config("nushell", active_dir)

    mock_warn.assert_not_called()


def test_warn_stale_config_linux_no_warning(tmp_path: Path):
    """On Linux, _warn_stale_config should never warn (no dual-path issue)."""
    home = tmp_path / "home"
    active_dir = home / ".config" / "nushell"
    active_dir.mkdir(parents=True)

    with (
        patch("core.merge.get_os", return_value="linux"),
        patch("core.merge.get_home_dir", return_value=home),
        patch("core.merge.log_warn") as mock_warn,
    ):
        _warn_stale_config("nushell", active_dir)

    mock_warn.assert_not_called()


def test_deploy_nushell_removes_disabled_integration_files(tmp_project: Path):
    """Switching to a profile that disables integrations should remove their init files."""
    config_dir = tmp_project / "nushell_cleanup_test"
    config_dir.mkdir()

    # Pre-create orphaned init files (simulating a prior deploy with all integrations)
    (config_dir / "oh-my-posh.nu").write_text("# old init\n", encoding="utf-8")
    (config_dir / "zoxide.nu").write_text("# old init\n", encoding="utf-8")

    # Deploy with all integrations disabled (minimal profile-like settings)
    minimal_settings = {
        "shells": {"nushell": True, "xonsh": False},
        "oh-my-posh": {"theme": "jblab_2021"},
        "integrations": {
            "oh-my-posh": False,
            "zoxide": False,
            "atuin": False,
            "carapace": False,
            "mise": False,
        },
        "commands": {
            "navigation": True,
            "fuzzy": True,
            "utilities": True,
            "sysinfo": True,
            "commands": True,
        },
        "fonts": {"nerd_font": "meslo", "auto_install": True},
        "backup": {"max_count": 5},
    }

    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge.load_settings", return_value=minimal_settings),
        patch("core.config.load_settings", return_value=minimal_settings),
    ):
        _deploy_nushell(config_dir, tmp_project)

    # Orphaned files should be removed
    assert not (config_dir / "oh-my-posh.nu").exists()
    assert not (config_dir / "zoxide.nu").exists()


def test_warn_stale_config_xonsh(tmp_path: Path):
    """On macOS with xonsh, check for user-custom.xsh as sentinel."""
    home = tmp_path / "home"
    active_dir = home / "Library" / "Application Support" / "xonsh"
    stale_dir = home / ".config" / "xonsh"
    active_dir.mkdir(parents=True)
    stale_dir.mkdir(parents=True)
    (stale_dir / "user-custom.xsh").write_text("# stale", encoding="utf-8")

    with (
        patch("core.merge.get_os", return_value="macos"),
        patch("core.merge.get_home_dir", return_value=home),
        patch("core.merge.log_warn") as mock_warn,
    ):
        _warn_stale_config("xonsh", active_dir)

    assert mock_warn.called
    msg = str(mock_warn.call_args)
    assert "xonsh" in msg


def test_preflight_validate_passes_clean_config(tmp_project: Path):
    """A valid config passes preflight without raising."""
    _preflight_validate(tmp_project)


def test_preflight_validate_raises_on_hard_error(tmp_project: Path):
    """A malformed aliases.toml stops the deploy before anything is written."""
    (tmp_project / "config" / "aliases.toml").write_text(
        'navigation = "not a table"\n', encoding="utf-8"
    )
    with pytest.raises(SystemExit):
        _preflight_validate(tmp_project)


def test_preflight_validate_warnings_do_not_raise(tmp_project: Path):
    """An unknown alias key is a warning -- deploy still proceeds AND the warning is surfaced."""
    (tmp_project / "config" / "aliases.toml").write_text(
        '[git]\ng = { command = "git", bogus = "x" }\n', encoding="utf-8"
    )
    with patch("core.merge.log_warn") as mock_warn:
        _preflight_validate(tmp_project)
    assert any("bogus" in str(c) for c in mock_warn.call_args_list)


def test_deploy_validate_false_skips_preflight(tmp_project: Path):
    """deploy(validate=False) trusts a command-level check and skips its own."""
    config_dir = tmp_project / "novalidate"
    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge._preflight_validate") as mock_validate,
    ):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project, validate=False)
    mock_validate.assert_not_called()


def test_deploy_validate_true_runs_preflight(tmp_project: Path):
    """deploy() validates by default so direct/standalone callers stay safe."""
    config_dir = tmp_project / "dovalidate"
    with (
        patch("core.merge.is_available", return_value=False),
        patch("core.merge._preflight_validate") as mock_validate,
    ):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)
    mock_validate.assert_called_once()


def test_deploy_aborts_on_invalid_config(tmp_project: Path):
    """deploy() itself refuses to run on a hard config error."""
    (tmp_project / "config" / "aliases.toml").write_text(
        'navigation = "not a table"\n', encoding="utf-8"
    )
    with pytest.raises(SystemExit):
        deploy("nushell", config_dir=tmp_project / "nu", project_dir=tmp_project)


def test_deploy_then_uninstall_removes_every_managed_file(tmp_project: Path):
    """Everything deploy writes is removed by uninstall -- driven by the real deploy, not a fixture."""
    from core.uninstall import _NUSHELL_MANAGED_FILES, uninstall_shell

    config_dir = tmp_project / "deploy_then_uninstall"

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    written = [f for f in _NUSHELL_MANAGED_FILES if (config_dir / f).exists()]
    assert written, "deploy wrote none of the managed files"

    # An install from before the header was added: the init file carries no marker.
    legacy = config_dir / "atuin.nu"
    legacy.write_text("source ~/.atuin.nu\n", encoding="utf-8")

    uninstall_shell("nushell", config_dir)

    left = [f for f in written if (config_dir / f).exists()]
    assert not left, f"uninstall left files behind: {left}"


def test_unescape_nu_double_quoted_round_trips_escape_nushell_path():
    """Every path escape_nushell_path emits must survive the round trip."""
    from core.merge import _unescape_nu_double_quoted
    from core.utils import escape_nushell_path, is_windows

    for raw in ['we"ird.nu', r"back\slash.nu", 'both"and' + chr(92) + "here.nu", "plain.nu"]:
        expected = raw.replace("\\", "/") if is_windows() else raw
        assert _unescape_nu_double_quoted(escape_nushell_path(raw)) == expected


def test_deploy_targets_intact_detects_missing_sourced_file(tmp_path: Path):
    """A config.nu sourcing a file that is gone means the last deploy is not intact."""
    from core.merge import _deploy_targets_intact

    config_dir = tmp_path / "nu"
    config_dir.mkdir()
    (config_dir / "env.nu").write_text("", encoding="utf-8")

    sourced = config_dir / "zoxide.nu"
    sourced.write_text("", encoding="utf-8")
    escaped = str(sourced).replace("\\", "\\\\").replace('"', '\\"')
    (config_dir / "config.nu").write_text(f'source "{escaped}"\n', encoding="utf-8")

    assert _deploy_targets_intact("nushell", config_dir) is True

    sourced.unlink()
    assert _deploy_targets_intact("nushell", config_dir) is False


def test_xonsh_targets_intact_detects_a_missing_loaded_file(tmp_path: Path, monkeypatch):
    """A moved repo makes the deployed .xonshrc silently skip files -- that must not count as intact."""
    from core import merge
    from core.utils import escape_python_path

    home = tmp_path / "home"
    home.mkdir()
    target = tmp_path / "aliases.xsh"
    target.write_text("", encoding="utf-8")
    escaped = escape_python_path(target)
    (home / ".xonshrc").write_text(f"_aliases_file = Path('{escaped}')\n", encoding="utf-8")

    monkeypatch.setattr(merge, "get_home_dir", lambda: home)
    assert merge._deploy_targets_intact("xonsh", tmp_path) is True

    target.unlink()
    assert merge._deploy_targets_intact("xonsh", tmp_path) is False


def test_deploy_regenerates_a_stub_once_its_tool_is_installed(tmp_project: Path):
    """Installing a tool does not change the source hash, so the skip check must
    notice the stub itself or the integration stays dead forever."""
    from core.merge import _STUB_MARKER, deploy

    config_dir = tmp_project / "nu-stub-refresh"
    config_dir.mkdir()

    with patch("core.merge.is_available", return_value=False):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    atuin_nu = config_dir / "atuin.nu"
    assert _STUB_MARKER in atuin_nu.read_text(encoding="utf-8")

    def _run_dispatch(cmd, **kwargs):
        if _resolved_tool_name(cmd) == "atuin":
            return subprocess.CompletedProcess(
                args=cmd, returncode=0, stdout="# real atuin init\n", stderr=""
            )
        return subprocess.CompletedProcess(
            args=cmd, returncode=0, stdout="2025-01-01 12:00:00 +0000\n", stderr=""
        )

    # Same source, so the hash is unchanged -- only the tool became available.
    with (
        patch("core.merge.is_available", side_effect=lambda t: t == "atuin"),
        patch("core.merge.subprocess.run", side_effect=_run_dispatch),
        patch("core.mise.shutil.which", return_value=None),
    ):
        deploy("nushell", config_dir=config_dir, project_dir=tmp_project)

    refreshed = atuin_nu.read_text(encoding="utf-8")
    assert _STUB_MARKER not in refreshed
    assert "real atuin init" in refreshed


def test_xonsh_deploy_fails_when_the_rc_cannot_reach_a_prompt(tmp_project: Path, tmp_path: Path):
    """nushell had this guard and xonsh did not, so a broken rc shipped silently."""
    from core.doctor import CheckResult
    from core.merge import _verify_global_xonsh_runtime

    broken = CheckResult("xonsh runtime", "fail", "deployed rc does not reach a prompt: boom")
    with (
        patch("core.doctor._check_xonsh_runtime", return_value=broken),
        pytest.raises(RuntimeError, match="does not reach a prompt"),
    ):
        _verify_global_xonsh_runtime()


def test_xonsh_runtime_check_reports_noise_as_warn_not_fail(tmp_path: Path):
    """Startup noise is worth surfacing but must not block a working deploy."""
    from core.doctor import _check_xonsh_runtime

    rc = tmp_path / ".xonshrc"
    rc.write_text("# rc\n", encoding="utf-8")
    noisy = subprocess.CompletedProcess(
        args=[], returncode=0, stdout="MY_SHELL_XONSH_OK\n", stderr="some deprecation\n"
    )
    with (
        patch("core.benchmark._shell_binary", return_value="xonsh"),
        patch("core.doctor.subprocess.run", return_value=noisy),
    ):
        assert _check_xonsh_runtime(rc).status == "warn"


def test_xonsh_runtime_check_reports_a_command_that_did_not_register(tmp_path: Path):
    """ "command not found: sysinfo" with a green doctor was the whole failure."""
    from core.doctor import _check_xonsh_runtime

    rc = tmp_path / ".xonshrc"
    rc.write_text("# rc\n", encoding="utf-8")
    proc = subprocess.CompletedProcess(
        args=[],
        returncode=0,
        stdout="MY_SHELL_XONSH_OK\nMY_SHELL_MISSING:sysinfo,commands\n",
        stderr="",
    )
    with (
        patch("core.benchmark._shell_binary", return_value="xonsh"),
        patch("core.doctor.subprocess.run", return_value=proc),
    ):
        result = _check_xonsh_runtime(rc)

    assert result.status == "fail"
    assert "sysinfo" in result.message


def test_xonsh_runtime_check_passes_when_every_command_registered(tmp_path: Path):
    from core.doctor import _check_xonsh_runtime

    rc = tmp_path / ".xonshrc"
    rc.write_text("# rc\n", encoding="utf-8")
    proc = subprocess.CompletedProcess(
        args=[], returncode=0, stdout="MY_SHELL_XONSH_OK\nMY_SHELL_MISSING:\n", stderr=""
    )
    with (
        patch("core.benchmark._shell_binary", return_value="xonsh"),
        patch("core.doctor.subprocess.run", return_value=proc),
    ):
        assert _check_xonsh_runtime(rc).status == "pass"


def test_generated_xonshrc_warns_when_a_command_module_fails_to_import(tmp_project: Path):
    """A silent `except ImportError: pass` leaves the user with a bare shell and no reason."""
    from core.merge import generate_xonsh_config

    content = generate_xonsh_config(config_dir=tmp_project / "xonsh", project_dir=tmp_project)

    assert "except ImportError" in content
    assert content.count("except ImportError:\n    pass") == 0
    assert "my-shell: commands unavailable" in content


def test_xonsh_runtime_check_warns_when_the_rc_was_never_deployed(tmp_path: Path):
    """Enabled + installed + no rc is the bare-shell failure, not a neutral note."""
    from core.doctor import _check_xonsh_runtime

    with patch("core.benchmark._shell_binary", return_value="xonsh"):
        result = _check_xonsh_runtime(tmp_path / "missing.xonshrc")

    assert result.status == "warn"
    assert result.fix and "setup --shell xonsh" in result.fix
