#!/bin/bash
set -euo pipefail

echo "=== Smoke Test ==="

# Both xonsh -c and nu -c run non-interactively and skip config files.
# Use explicit flags to load them so aliases/env vars are available.
XONSH_RC="$HOME/.xonshrc"
NU_ENV="$HOME/.config/nushell/env.nu"
NU_CONFIG="$HOME/.config/nushell/config.nu"
SHELL_STDERR=$(mktemp)
trap 'rm -f "$SHELL_STDERR"' EXIT

run_clean() {
    label=$1
    shift
    : >"$SHELL_STDERR"
    "$@" 2>"$SHELL_STDERR"
    if test -s "$SHELL_STDERR"; then
        cat "$SHELL_STDERR" >&2
        echo "ERROR: $label wrote startup diagnostics" >&2
        exit 1
    fi
}

# Verify xonsh starts and aliases exist
echo "Testing xonsh..."
run_clean xonsh mise exec -- xonsh --rc "$XONSH_RC" -c "
print('xonsh started OK')
assert 'gs' in aliases, 'git status alias missing'
assert '..' in aliases, 'navigation alias missing'
print('xonsh aliases OK')
"

# Verify nushell starts and config was generated by my-shell
echo "Testing nushell..."
run_clean nushell mise exec -- nu --env-config "$NU_ENV" --config "$NU_CONFIG" -c "
print 'nushell started OK'
let cfg_path = \$nu.config-path
let content = (open \$cfg_path)
if (\$content | str contains 'Generated by my-shell') {
    print 'nushell config generated by my-shell OK'
} else {
    print 'ERROR: config.nu not generated by my-shell'
    exit 1
}
if (\$content | str contains 'LAYER 2') {
    print 'nushell three-layer architecture OK'
} else {
    print 'ERROR: config.nu missing layer markers'
    exit 1
}
"

# Verify nushell env vars
echo "Testing nushell env vars..."
run_clean nushell mise exec -- nu --env-config "$NU_ENV" --config "$NU_CONFIG" -c "
  if (\$env.MY_SHELL_DIR | is-empty) { print 'ERROR: MY_SHELL_DIR empty'; exit 1 }
  if not ('MY_SHELL_VERSION' in \$env) { print 'ERROR: MY_SHELL_VERSION not set'; exit 1 }
  print \$'nushell env vars OK, version=(\$env.MY_SHELL_VERSION)'
"

# Verify sysinfo command
echo "Testing nushell sysinfo..."
run_clean nushell mise exec -- nu --env-config "$NU_ENV" --config "$NU_CONFIG" -c "sysinfo | ignore; print 'sysinfo OK'"

# Verify xonsh env vars
echo "Testing xonsh env vars..."
run_clean xonsh mise exec -- xonsh --rc "$XONSH_RC" -c "
assert \$MY_SHELL_DIR, 'MY_SHELL_DIR not set'
assert 'MY_SHELL_VERSION' in __xonsh__.env, 'MY_SHELL_VERSION not set'
print('xonsh env vars OK')
"

# Verify xonsh sysinfo alias
echo "Testing xonsh sysinfo..."
run_clean xonsh mise exec -- xonsh --rc "$XONSH_RC" -c "
_sysinfo = aliases.get('sysinfo')
assert _sysinfo is not None, 'sysinfo not registered'
print('xonsh sysinfo OK')
"

# Verify xontribs actually installed and loadable
echo "Testing xontrib loading..."
run_clean xonsh mise exec -- xonsh --rc "$XONSH_RC" -c "
xontrib load abbrevs
print('xontrib load OK')
"

echo "=== All smoke tests passed ==="
