"""Interactive setup wizard for my-shell.

Detects installed shells, available tools, and lets users pick their
configuration. Writes config/settings.local.toml and runs setup.
"""

from pathlib import Path

import typer

from .registry import INTEGRATION_TOOLS
from .utils import get_project_dir, is_available, log_header, log_info, log_step, log_success


def _detect_shells() -> dict[str, bool]:
    """Detect which shells are installed."""
    return {
        "nushell": is_available("nu"),
        "xonsh": is_available("xonsh"),
    }


def _detect_tools() -> dict[str, bool]:
    """Detect which integration tools are installed."""
    return {name: is_available(info.binary) for name, info in INTEGRATION_TOOLS.items()}


def _list_omp_themes(project_dir: Path) -> list[str]:
    """List available oh-my-posh themes."""
    themes_dir = project_dir / "shells" / "shared" / "oh-my-posh" / "themes"
    if not themes_dir.exists():
        return []
    return sorted(f.stem.replace(".omp", "") for f in themes_dir.glob("*.omp.json"))


def run_init_wizard(project_dir: Path | None = None) -> None:
    """Run the interactive setup wizard."""
    root = project_dir or get_project_dir()

    log_step("my-shell Setup Wizard")
    print()

    log_header("  Step 1: Shell Detection")
    shells = _detect_shells()
    selected_shells: list[str] = []
    for shell, available in shells.items():
        status = "found" if available else "not found"
        mark = "\033[32m\u2714\033[0m" if available else "\033[31m\u2718\033[0m"
        print(f"  {mark} {shell}: {status}")
        if available:
            selected_shells.append(shell)

    if not selected_shells:
        print("\n  No shells detected! Install nushell or xonsh first.")
        print("  Run: my-shell install --shell all")
        return

    configure_all = typer.confirm(
        f"\n  Configure {', '.join(selected_shells)}?",
        default=True,
    )
    if not configure_all:
        return

    log_header("  Step 2: Tool Detection")
    tools = _detect_tools()
    available_integrations: list[str] = []
    for name, avail in tools.items():
        mark = "\033[32m\u2714\033[0m" if avail else "\033[2m\u2716\033[0m"
        print(f"  {mark} {name}")
        if avail:
            available_integrations.append(name)

    omp_theme = "jblab_2021"
    if "oh-my-posh" in available_integrations:
        log_header("  Step 3: Oh-My-Posh Theme")
        themes = _list_omp_themes(root)
        if themes:
            print(f"  Available themes: {', '.join(themes)}")
            custom_theme = typer.prompt(
                "  Theme",
                default="jblab_2021",
                show_default=True,
            )
            import re

            omp_theme = re.sub(r"[^a-zA-Z0-9_-]", "", custom_theme)
        else:
            log_info("  Using default theme: jblab_2021")

    nerd_font = "meslo"
    if "oh-my-posh" in available_integrations:
        log_header("  Step 3b: Nerd Font")
        from .fonts import NERD_FONTS

        font_names = list(NERD_FONTS.keys())
        print(f"  Available: {', '.join(font_names)} (default: meslo)")
        custom_font = typer.prompt(
            "  Font",
            default="meslo",
            show_default=True,
        )
        if custom_font in NERD_FONTS:
            nerd_font = custom_font
        else:
            log_info(f"  Unknown font '{custom_font}', using default: meslo")

    log_header("  Step 4: Generating configuration")

    xonsh_enabled = "xonsh" in selected_shells

    lines: list[str] = [
        "# Generated by `my-shell init`",
        "",
        "[shells]",
        "nushell = true",
        f"xonsh = {'true' if xonsh_enabled else 'false'}",
        "",
        "[oh-my-posh]",
        f'theme = "{omp_theme}"',
        "",
        "[integrations]",
    ]

    all_integrations = list(INTEGRATION_TOOLS.keys())
    for name in all_integrations:
        enabled = name in available_integrations
        lines.append(f"{name} = {'true' if enabled else 'false'}")

    lines.extend(
        [
            "",
            "[fonts]",
            f'nerd_font = "{nerd_font}"',
            "auto_install = true",
            "",
            "[commands]",
            "navigation = true",
            "fuzzy = true",
            "utilities = true",
            "sysinfo = true",
            "commands = true",
            "",
        ]
    )

    local_path = root / "config" / "settings.local.toml"
    content = "\n".join(lines)

    # Show the config before writing it, then confirm.
    from rich.console import Console
    from rich.syntax import Syntax

    Console().print(Syntax(content, "toml", theme="monokai", line_numbers=False))
    if not typer.confirm(f"\n  Write {local_path.name}?", default=True):
        log_info("Setup cancelled -- no configuration written.")
        return
    local_path.write_text(content, encoding="utf-8")
    log_success(f"Configuration saved to {local_path}")

    run_setup = typer.confirm("\n  Run setup now?", default=True)
    if run_setup:
        from .config import get_config_dir
        from .merge import _preflight_validate, deploy

        # Validate the (global) config once, then deploy each shell.
        _preflight_validate(root)
        print()
        deployed: list[str] = []
        for shell in selected_shells:
            log_step(f"Setting up {shell}...")
            try:
                deploy(shell, force=True, validate=False)
                deployed.append(shell)
            except Exception as exc:
                print(f"  Setup failed for {shell}: {exc}")
        print()
        log_success("Setup complete!")

        # Recap: where each shell landed and the exact command to start it.
        log_header("  You're all set")
        for shell in deployed:
            bin_name = "nu" if shell == "nushell" else "xonsh"
            log_info(f"{shell}: config at {get_config_dir(shell)}")
            log_info(f"  start it with: exec {bin_name}")
    else:
        log_info("Run `my-shell setup` when ready to deploy.")
