"""Configuration profiles for my-shell.

Profiles define presets for which integrations and commands are enabled.
Stored in config/profiles.toml, applied via `my-shell setup --profile <name>`.
"""

import re
from pathlib import Path
from typing import Any

from .config import _DEFAULT_SETTINGS, load_toml
from .utils import get_project_dir, log_info, log_success

_DEFAULT_PROFILES: dict[str, dict[str, Any]] = {
    "minimal": {
        "integrations": ["zoxide"],
        "commands": ["navigation", "utilities"],
    },
    "full": {
        "integrations": ["oh-my-posh", "zoxide", "atuin", "carapace", "mise"],
        "commands": ["navigation", "fuzzy", "utilities", "sysinfo", "commands"],
    },
}


def load_profiles(project_dir: Path | None = None) -> dict[str, dict[str, Any]]:
    """Load profiles from config/profiles.toml, falling back to defaults."""
    root = project_dir or get_project_dir()
    path = root / "config" / "profiles.toml"

    if path.exists():
        data = load_toml(path)
        user_profiles = data.get("profiles", {})
        if not isinstance(user_profiles, dict):
            raise ValueError(
                f"profiles.toml: 'profiles' must be a table, got {type(user_profiles).__name__}"
            )
        # Merge over the built-ins so a user-defined profile adds to minimal/full, not replaces them.
        return {**_DEFAULT_PROFILES, **user_profiles}

    return dict(_DEFAULT_PROFILES)


def _resolve_profile(
    profiles: dict[str, dict[str, Any]], name: str, visited: set[str] | None = None
) -> dict[str, Any]:
    """Resolve a profile, following 'inherits' chains."""
    if visited is None:
        visited = set()
    if name in visited:
        raise ValueError(f"Circular profile inheritance detected: {name}")
    visited.add(name)

    profile = profiles.get(name)
    if profile is None:
        known = ", ".join(sorted(profiles))
        raise ValueError(f"Unknown profile: {name}. Known profiles: {known}")

    if "inherits" in profile:
        parent = _resolve_profile(profiles, profile["inherits"], visited)
        merged = dict(parent)
        for key, value in profile.items():
            if key != "inherits":
                merged[key] = value
        return merged

    return dict(profile)


def active_profile(project_dir: Path | None = None) -> str | None:
    """Return the last-applied profile name, read from the settings.local.toml header.

    apply_profile() writes `# Auto-generated by `my-shell setup --profile <name>``
    as the first line; None means no profile was applied (or the wizard wrote it).
    """
    root = project_dir or get_project_dir()
    path = root / "config" / "settings.local.toml"
    if not path.exists():
        return None
    try:
        first_line = path.read_text(encoding="utf-8").splitlines()[0]
    except OSError, IndexError:
        return None
    match = re.search(r"setup --profile ([\w-]+)", first_line)
    return match.group(1) if match else None


_SECTION_HEADER_RE = re.compile(r"^\s*\[([^\]]+)\]")


def _lines_outside_sections(path: Path, drop: set[str]) -> list[str]:
    """Return the lines of *path* that belong to no section in *drop*.

    Keeps every other setting the user put in settings.local.toml, including
    comments and top-level keys, so applying a profile does not wipe them.
    """
    if not path.exists():
        return []

    kept: list[str] = []
    current: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        match = _SECTION_HEADER_RE.match(line)
        if match:
            current = match.group(1).partition(".")[0].strip()
        if current in drop or line.startswith("# Auto-generated by "):
            continue
        kept.append(line)

    while kept and not kept[-1].strip():
        kept.pop()
    return kept


def apply_profile(name: str, project_dir: Path | None = None) -> None:
    """Apply a profile by rewriting the [integrations] and [commands] sections.

    Every other section and key in settings.local.toml is preserved.
    """
    root = project_dir or get_project_dir()
    profiles = load_profiles(root)
    resolved = _resolve_profile(profiles, name)

    local_path = root / "config" / "settings.local.toml"
    preserved = _lines_outside_sections(local_path, {"integrations", "commands"})

    lines: list[str] = [f"# Auto-generated by `my-shell setup --profile {name}`", ""]
    if preserved:
        lines.extend(preserved)
        lines.append("")

    # Integrations
    all_integrations = list(_DEFAULT_SETTINGS["integrations"].keys())
    enabled_integrations = resolved.get("integrations", all_integrations)

    lines.append("[integrations]")
    for tool in all_integrations:
        enabled = tool in enabled_integrations
        lines.append(f"{tool} = {'true' if enabled else 'false'}")
    lines.append("")

    # Commands
    all_commands = list(_DEFAULT_SETTINGS["commands"].keys())
    enabled_commands = resolved.get("commands", all_commands)

    lines.append("[commands]")
    for cmd in all_commands:
        enabled = cmd in enabled_commands
        lines.append(f"{cmd} = {'true' if enabled else 'false'}")
    lines.append("")

    local_path.write_text("\n".join(lines), encoding="utf-8")
    log_success(f"Applied profile '{name}' to {local_path}")
    log_info(f"Integrations: {', '.join(enabled_integrations)}")
    log_info(f"Commands: {', '.join(enabled_commands)}")
