"""Uninstall deployed my-shell configuration files."""

from pathlib import Path

from .registry import INTEGRATION_TOOLS
from .utils import get_home_dir, guard_test_write, log_info, log_success, log_warn

_MY_SHELL_MARKER = "Generated by my-shell"

# Files a user could plausibly have hand-written before adopting my-shell.
_NUSHELL_HANDWRITABLE_FILES = ["config.nu", "env.nu"]

# Integration inits come from the registry deploy writes them from; only my-shell writes these.
_NUSHELL_INTEGRATION_FILES = [
    info.nushell_init_file for info in INTEGRATION_TOOLS.values() if info.nushell_init_file
]

_NUSHELL_MANAGED_FILES = _NUSHELL_HANDWRITABLE_FILES + _NUSHELL_INTEGRATION_FILES

_NUSHELL_USER_FILES = [
    "user-custom.nu",
    "user-env.nu",
]

# xonsh: the rc lives at ~/.xonshrc (home), user-custom in the shell config dir
_XONSH_MANAGED_HOME_FILES = [".xonshrc"]
_XONSH_USER_FILES = ["user-custom.xsh"]


def _is_my_shell_file(fpath: Path) -> bool:
    """True when *fpath* carries the header my-shell writes into files it generates."""
    try:
        return _MY_SHELL_MARKER in fpath.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def _remove(fpath: Path, removed: list[str]) -> None:
    guard_test_write(fpath, f"remove {fpath.name}")
    fpath.unlink()
    log_success(f"Removed: {fpath}")
    removed.append(str(fpath))


def _remove_if_generated(fpath: Path, removed: list[str]) -> None:
    """Delete *fpath* only when my-shell generated it; otherwise keep and report it."""
    if not _is_my_shell_file(fpath):
        log_warn(f"Kept (not generated by my-shell): {fpath}")
        return
    _remove(fpath, removed)


def uninstall_shell(shell: str, config_dir: Path, *, keep_custom: bool = True) -> list[str]:
    """Remove deployed my-shell configuration files for a shell.

    Files that do not carry the my-shell header are kept -- my-shell never
    generated them. A backup is taken first so the removal can be rolled back.
    """
    if shell not in ("nushell", "xonsh"):
        log_warn(f"Unknown shell: {shell}")
        return []

    guard_test_write(config_dir, f"uninstall {shell} config")

    from .backup import backup_before_deploy

    backup_before_deploy(shell, config_dir)

    if shell == "nushell":
        return _uninstall_nushell(config_dir, keep_custom=keep_custom)
    return _uninstall_xonsh(config_dir, keep_custom=keep_custom)


def _uninstall_nushell(config_dir: Path, *, keep_custom: bool = True) -> list[str]:
    """Remove deployed nushell config files."""
    removed: list[str] = []

    for fname in _NUSHELL_HANDWRITABLE_FILES:
        fpath = config_dir / fname
        if fpath.exists():
            _remove_if_generated(fpath, removed)

    # No marker check: installs from before the header was added still leave these behind.
    for fname in _NUSHELL_INTEGRATION_FILES:
        fpath = config_dir / fname
        if fpath.exists():
            _remove(fpath, removed)

    if not keep_custom:
        for fname in _NUSHELL_USER_FILES:
            fpath = config_dir / fname
            if fpath.exists():
                _remove(fpath, removed)
    else:
        for fname in _NUSHELL_USER_FILES:
            fpath = config_dir / fname
            if fpath.exists():
                log_info(f"Kept: {fpath}")

    return removed


def _uninstall_xonsh(config_dir: Path, *, keep_custom: bool = True) -> list[str]:
    """Remove deployed xonsh config files."""
    removed: list[str] = []
    home = get_home_dir()

    for fname in _XONSH_MANAGED_HOME_FILES:
        fpath = home / fname
        if fpath.exists():
            _remove_if_generated(fpath, removed)

    for fname in _XONSH_USER_FILES:
        fpath = config_dir / fname
        if not fpath.exists():
            continue
        if keep_custom:
            log_info(f"Kept: {fpath}")
        else:
            _remove(fpath, removed)

    return removed
