#!/bin/sh
# Deep post-install verification for Unix (Linux / macOS)
# Usage: INSTALL_DIR=/path/to/my-shell bash scripts/verify-install.sh

set -eu

INSTALL_DIR="${INSTALL_DIR:?INSTALL_DIR must be set}"

fail() { printf 'FAIL: %s\n' "$1" >&2; exit 1; }
pass() { printf 'PASS: %s\n' "$1"; }

# ── Artifact checks ─────────────────────────────────────────────
test -d "$INSTALL_DIR/.git"      || fail ".git not found"
test -f "$INSTALL_DIR/mise.toml" || fail "mise.toml not found"
pass "repository structure intact"

cd "$INSTALL_DIR"

# ── CLI smoke tests ─────────────────────────────────────────────
mise exec -- uv run my-shell --help    >/dev/null || fail "my-shell --help failed"
pass "my-shell --help"

mise exec -- uv run my-shell detect    >/dev/null || fail "my-shell detect failed"
pass "my-shell detect"

mise exec -- uv run my-shell validate  >/dev/null || fail "my-shell validate failed"
pass "my-shell validate"

mise exec -- uv run my-shell version   >/dev/null || fail "my-shell version failed"
pass "my-shell version"

# ── Deployed config ─────────────────────────────────────────────
NU_DIR=$(mise exec -- uv run python -c 'from core.utils import get_nushell_config_dir; print(get_nushell_config_dir())') \
    || fail "could not resolve the nushell config directory"
test -f "$NU_DIR/config.nu" || fail "nushell config was not deployed to $NU_DIR"
grep -q 'Generated by my-shell' "$NU_DIR/config.nu" \
    || fail "$NU_DIR/config.nu is missing the 'Generated by my-shell' marker"
pass "nushell config deployed to $NU_DIR"

# ── Render produces output ──────────────────────────────────────
mise exec -- uv run my-shell render --shell nushell || fail "my-shell render --shell nushell failed"
test -f shells/nushell/aliases.nu || fail "aliases.nu not generated after render"

# Verify the rendered file has content (not empty)
test -s shells/nushell/aliases.nu || fail "aliases.nu is empty"
pass "render produced aliases.nu"

# ── Runtime startup contract ────────────────────────────────────
NU_STDERR=$(mktemp)
trap 'rm -f "$NU_STDERR"' EXIT
# shellcheck disable=SC2016  # Nushell expression; the POSIX shell must not expand it.
if ! mise exec -- nu -l -c '$env.CMD_DURATION_MS = 42; do $env.PROMPT_COMMAND | ignore' \
    >/dev/null 2>"$NU_STDERR"; then
    sed -n '1,80p' "$NU_STDERR" >&2
    fail "nushell failed during a post-command prompt"
fi
if test -s "$NU_STDERR"; then
    sed -n '1,80p' "$NU_STDERR" >&2
    fail "nushell wrote startup or prompt diagnostics"
fi
pass "nushell startup and second prompt are clean"

mise exec -- uv run my-shell doctor >/dev/null || fail "my-shell doctor failed"
pass "my-shell doctor"

echo ""
echo "All install verifications passed"
