# Deep post-install verification for Windows
# Usage: $env:INSTALL_DIR = "C:\path\to\my-shell"; .\scripts\verify-install.ps1

$ErrorActionPreference = "Stop"

if (-not $env:INSTALL_DIR) {
    Write-Error "INSTALL_DIR must be set"; exit 1
}
$InstallDir = $env:INSTALL_DIR

function Fail($msg) { Write-Error "FAIL: $msg"; exit 1 }
function Pass($msg) { Write-Host "PASS: $msg" -ForegroundColor Green }

# Refresh PATH from registry (mise/uv installed by install.ps1)
$userPath = [System.Environment]::GetEnvironmentVariable("PATH", "User")
if ($userPath) { $env:PATH = "$userPath;$env:PATH" }

# -- Artifact checks --------------------------------------------------
if (-not (Test-Path "$InstallDir\.git")) { Fail ".git not found" }
if (-not (Test-Path "$InstallDir\mise.toml")) { Fail "mise.toml not found" }
Pass "repository structure intact"

Push-Location $InstallDir
try {
    # -- CLI smoke tests -----------------------------------------------
    mise exec -- uv run my-shell --help | Out-Null
    if ($LASTEXITCODE -ne 0) { Fail "my-shell --help failed" }
    Pass "my-shell --help"

    mise exec -- uv run my-shell detect | Out-Null
    if ($LASTEXITCODE -ne 0) { Fail "my-shell detect failed" }
    Pass "my-shell detect"

    mise exec -- uv run my-shell validate | Out-Null
    if ($LASTEXITCODE -ne 0) { Fail "my-shell validate failed" }
    Pass "my-shell validate"

    mise exec -- uv run my-shell version | Out-Null
    if ($LASTEXITCODE -ne 0) { Fail "my-shell version failed" }
    Pass "my-shell version"

    # -- Deployed config -----------------------------------------------
    $nuDir = mise exec -- uv run python -c "from core.utils import get_nushell_config_dir; print(get_nushell_config_dir())"
    if ($LASTEXITCODE -ne 0) { Fail "could not resolve the nushell config directory" }
    $nuConfig = Join-Path $nuDir "config.nu"
    if (-not (Test-Path $nuConfig)) { Fail "nushell config was not deployed to $nuConfig" }
    if (-not (Select-String -Path $nuConfig -Pattern "Generated by my-shell" -Quiet)) {
        Fail "$nuConfig is missing the 'Generated by my-shell' marker"
    }
    Pass "nushell config deployed to $nuDir"

    # -- Render produces output ----------------------------------------
    mise exec -- uv run my-shell render --shell nushell
    if ($LASTEXITCODE -ne 0) { Fail "my-shell render --shell nushell failed" }

    if (-not (Test-Path "shells\nushell\aliases.nu")) { Fail "aliases.nu not generated after render" }
    if ((Get-Item "shells\nushell\aliases.nu").Length -eq 0) { Fail "aliases.nu is empty" }
    Pass "render produced aliases.nu"

    Write-Host ""
    Write-Host "All install verifications passed"
} finally {
    Pop-Location
}
